### PR TITLE
chore: Return the appropriate status code when testing

### PR DESCRIPTION
**Pull request by fabiomadge**
This change enables us to detect crashes more reliably. To support tests that require the previous default, there is now `dafny_0`

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Comment by fabiomadge** [comment]
I probably didn't apply the label early enough.

**Comment by robin-aws** [comment]
This is awesome, and now I'm curious to see the script you used to apply the changes. :)

My only ask is that we add `%dafny_0` to `lit.site.cfg` as well, since that should be quick and I know some contributors are still using `lit` instead of the xUnit-based runner (until we deliver https://github.com/dafny-lang/dafny/issues/2033)

> I probably didn't apply the label early enough.

If having to push a dummy commit to kick the CI again in this situation becomes a recurring irritation, I believe we can set things up so that a workflow triggers when a label is applied to a PR.

**Comment by fabiomadge** [comment]
I did add it to both xUnit and lit, but it's hard to miss among the literal hundreds of other files.

```Python
FILES = ["wishlist/FunctionEquality.dfy',"]

def replace(s, a, b, i):
    if i <= 0:
        return s
    start = -len(a)
    while i > 0:
        start = s.find(a, start+len(a))
        if start == -1:
            return s
        i -= 1
    return s[:start] + b + s[start+len(a):]


for relative in FILES:
    full = f'/Users/fmadge/Documents/dafny/Test/{relative}'
    f = open(full, 'r')
    before = f.read()
    f.close()
    f = open(full, 'w')
    current = before
    def check():
        f.seek(0)
        f.write(current)
        f.flush()
        return os.system(f'lit {full} &> /dev/null') == 0
    i = 0
    while not check():
        i += 1
        current = replace(before, '%dafny', '%dafny_0', i)
        if current == before:
            print(f'failed fixing {relative} and restored')
            f.close()
            f = open(full, 'w')
            f.write(before)
            break
    if not current == before:
        print(f'fixed {relative}')
    f.close()
```

**Comment by cpitclaudel** [comment]
Our docs say that `/countVerificationErrors` is deprecated; instead of that, maybe we could use use `|| true` on each line that we expect to exist with a non-zero exit code?

**Comment by fabiomadge** [comment]
The burden of keeping this option around doesn't seems too high, and luckily we control our own destiny in that regard.

**Comment by robin-aws** [comment]
> Our docs say that `/countVerificationErrors` is deprecated; instead of that, maybe we could use use `|| true` on each line that we expect to exist with a non-zero exit code?

This is a good point: `|| true` already works with the xUnit runner (https://github.com/dafny-lang/dafny/blob/master/Test/DafnyTests/TestAttribute.dfy#L2), and is more self-documenting than `%dafny_0`. Assuming you can easily apply that suffix with your script instead, I'd prefer that simpler solution!

> I did add it to both xUnit and lit, but it's easy to miss among the hundreds of other files.

Whoops, clearly it is. :)

**Comment by fabiomadge** [comment]
The script isn't prefect, so it would be easier to expand `dafny_0` in the proposed way. I see value in less complex expressions in the test files.

**Review by robin-aws — APPROVED** [review]
Although I have plans for a different, deeper solution to this as part of https://github.com/dafny-lang/dafny/issues/1770, this is still great forwards progress and will save time in converting test cases in that work. Thanks for taking this on!

**Pull request merged**
