### PR TITLE
Check well-formedness of receiver in method calls

### LINKED ISSUE #448: soundness issue: uninitialized object variable of non-nullable type
I expect this code to give some kind of error:
```
class C { 
  method m() {
  }
}

method Main() {
  var c: C;
  c.m();
}
```

As you can see, the variable `c` will be `null` when `c.m()` is called.

However, it verifies with no issue, and when run, gives a `NullReferenceException`:

```
$ dafny foo.dfy 
Dafny 2.3.0.10506

Dafny program verifier finished with 1 verified, 0 errors
Compiled assembly into foo.exe

$ mono foo.exe

Unhandled Exception:
System.NullReferenceException: Object reference not set to an instance of an object
  at _module.__default.Main () [0x00002] in <5ad62780ed7046e8ac2d47879dff4d86>:0 
[ERROR] FATAL UNHANDLED EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object
  at _module.__default.Main () [0x00002] in <5ad62780ed7046e8ac2d47879dff4d86>:0 
```

### PR DESCRIPTION
**Pull request by RustanLeino**
Fixes #448

### CODE REVIEW

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 01eec8dee4b43f83b187988b2f5da1cfff4d7178
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=5ef3847a-d0c9-4b33-a8b3-60f6dc5867bf%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by RustanLeino** [comment]
The two failing test cases (`Lucas-down.dfy` and `git-issue223.transcript`) go through on my machine.

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 01eec8dee4b43f83b187988b2f5da1cfff4d7178
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=3ce1972c-425a-487a-b8a0-7a5489ae9fb6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 79c7e63c0745836b2716d365216c0227373bd58c
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1e1f6186-b483-4cde-8bc6-52da3bb43210%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
