### PR TITLE
feat: Add bounded polymorphism

### LINKED ISSUE #5211: Support for bounded polymorphism / trait bounds
### Summary

Many languages provide the ability to put bounds on type parameters. For example, Java allows [bounded type parameters](https://docs.oracle.com/javase/tutorial/java/generics/bounded.html), Rust allows [bounding](https://doc.rust-lang.org/rust-by-example/generics/bounds.html) type parameters and lifetimes, and C# allows [constraints on type parameters]. When modeling standard libraries in such languages, types making use of such features are hard to model in Dafny. 

It would be useful for interfacing with libraries in various target languages if Dafny had support for constraints on type parameters. It would also allow uses to be more precise in their type signatures, for example by specifying that a given type parameter needs to implement multiple traits (without needing to create a new trait definition combining this particular combination of traits).

### Background and Motivation

As a motivating example, consider the [`Peekable`](https://doc.rust-lang.org/std/iter/struct.Peekable.html) trait from the Rust standard library:

```rust
pub struct Peekable<I>
where
    I: [Iterator](https://doc.rust-lang.org/std/iter/trait.Iterator.html),{ /* private fields */ } {
    ..
    pub fn peek() -> Option<&<I as Iterator>::Item>
    ..
}

// values of type `Peekable<..> via:
trait Iterator {
  type Item;
  ..
  pub fn peekable(self) -> Peekable<Self>
}
```

Writing a Dafny binding to the `Peekable`/`Iterator` APIs is currently not feasible since the type parameter to `Peekable` cannot be expressed in Dafny. 

Given that this is the prevalent abstraction pattern in Rust, used in places where object-oriented languages would often use subtyping / inheritance, I would expect this problem to occur with other commonplace Rust libraries as well.

### Proposed Feature

Dafny could offer a similar feature and syntax as other languages. For example, whenever type parameters are specified, Dafny could allow the following:
```
trait SomeTrait {
  method someTraitMethod()
}
method foo<T: SomeTrait>(arg: T) {
  arg.someTraitMethod();
}
```

Type-checking could follow the same implementation strategies as for Java, C#, or Rust. I'm not sure whether this feature would have non-trivial interactions with the verifier, given that it is purely a type system extension.

### Alternatives

When writing code that interfaces with these parts of the Rust standard library, a user is instead forced to manually create monomorphized instances of `Peekable` instead. This creates a maintenance burden linear in the number of type parameters a type like `Peekable` is used with and  requires error-prone copying and pasting of similar code. Additionally, one would have to redeclare all members of the trait for each monomorphized instance on the Dafny side.

Other solutions could include automatic translation of Dafny traits to bounded type parameters in Rust, but this does not address cases like the above where the type parameter cannot be specified at the Dafny level.

### PR DESCRIPTION
**Pull request by RustanLeino**
# Description

This PR adds bounded polymorphism to the Dafny language. This feature allows any formal type parameter to be declared with a suffix of any number of

```
extends Type
```

clauses, where `Type` is any trait or subset type thereof. At call sites, the actual type arguments are checked to be subtypes of the listed type bounds. Where the formal type parameters are in scope, an expression whose type is the type parameter can be converted to a supertype of any of the type bounds by an explicit type conversion (`as`). In some cases, the type conversion is inferred automatically and can then be omitted from the program text.

The feature requires `--type-system-refresh` for full functionality.

Closes #5211 

# Example

For `test.dfy` being the program

``` dafny
trait Printable {
  method Print()
}

method SelectPrintReturn<T extends Printable>(operateOnLeft: bool, left: T, right: T) returns (r: T)
{
  r := if operateOnLeft then left else right;
  (r as Printable).Print();
}

datatype Dt extends Printable = Dt(u: int) {
  method Print() {
    print u, "\n";
  }
}

method Main() {
  var d0 := Dt(500);
  var d1 := Dt(702);
  var e0 := SelectPrintReturn(true, d0, d1); // 500
  var e1 := SelectPrintReturn(false, d0, d1); // 702
  print (d0, d1) == (d0, d1), "\n"; // true
}
```

we get:

```
> dafny run test.dfy --type-system-refresh --general-traits=datatype

Dafny program verifier finished with 3 verified, 0 errors
500
702
true
```

# Bonus

The PR also

* suppresses near-identical error messages (in particular, it reports only one error for conditions that split into several checks, like the type equality `A==B` which turns into both `A :> B` and `B >: A`)

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Comment by ssomayyajula** [comment]
Reporting some issues on behalf of @erniecohen:

1. If `X extends T` and one has `x: X`, then one frequently has to assert that `x is T`. In fact, I myself can't get this to check:

```
trait T {}

function F<X extends T>(x: X): T {
  assert x is T; x // x is not assignable to T
}
```

Is there a missing constraint during type inference?

3. The following doesn't check.

```
trait T { 
    static const z := 0
}
trait U<X extends T> {
    static const z := X.z // unresolved identifier: X
}
```

**Comment by RustanLeino** [comment]
Thanks for the feedback and the example code.

Regarding point 1:

The only way I'm able to reproduce getting an "not assignable" type-checking error is if I use the old type system. To use `is` with more types (and, in particular, with a type parameter), you must use the new type system (`--type-system-refresh`). I think this explains the behavior of point 1.

However, even with `--type-system-refresh`, the code in point 1 revealed some crashes and malformed generated code in the verifier and compilers (some with `--general-traits=legacy` and some with `--general-traits=datatype`. I have now fixed those bugs in the new commits.

**Comment by RustanLeino** [comment]
Regarding point 2:

`X.z` is not support when `X` is a type parameter. To reference the static member of the trait `T` that `X` extends, write `T.z`.

**Comment by RustanLeino** [comment]
Regarding point 3:  Thanks. Evidently, this was a problem with `if-then-else` expressions involving non-reference trait types already in Dafny 4.6.0. I reported the problem in Issue #5570 and fixed it.

**Comment by ssomayyajula** [comment]
Thanks! Lastly, @ecohen is reporting that the following code...

```
module Foo.Bar {

trait {:termination false}Dom<T> {
    predicate  has(t:T)
    ghost predicate isMe(r:Dom<T>) 
    function and(d:Dom<T>):(r:Dom<T>) requires isMe(d) ensures isMe(r) 
}
}
module Foo {
import opened Bar
datatype Prod<T, L extends Dom<T>, R extends Dom<T>> extends Dom<T> = Prod(l:L,r:R) {
    
    predicate has(t:T)  { (l as Dom<T>).has(t) && (r as Dom<T>).has(t) } 
    ghost predicate isMe(d:Dom<T>) { 
        && d is Prod<T,L,R> 
        && var d1 := d as Prod<T,L,R>; 
           ((l as Dom<T>).isMe(d1.l) && (r as Dom<T>).isMe(d1.r)) 
    }
    function and(d:Dom<T>):(r:Dom<T>) requires isMe(d) ensures isMe(r) {
        var d1 := d as Prod<T,L,R>;
        var p := Prod((l as Dom<T>).and(d1.l),(r as Dom<T>).and(d1.r));
        assert isMe(p) by {
          assert (l as Dom<T>).isMe(d1.l);
          assert (r as Dom<T>).isMe(d1.r);
        }
        p
    }
}
}
```

...produces 

```
/root/Test-bounded-poly.dfy(22,15): Error: assertion might not hold
   |
22 |         assert isMe(p) by {
   |                ^^^^^^^

/root/Test-bounded-poly.dfy(22,20): Related location: this proposition could not be proved
   |
22 |         assert isMe(p) by {
   |                     ^
```

Looks like the wrong token was assigned for the related location?

**Comment by RustanLeino** [comment]
I added Ernie's new bug report into Issue https://github.com/dafny-lang/dafny/issues/5586 and fixed it in PR https://github.com/dafny-lang/dafny/pull/5587.

**Review by ssomayyajula — APPROVED** [review]

**Review by ssomayyajula — APPROVED** [review]

**Pull request merged**
