### PR TITLE
Change "semi expected" to "semicolon expected"

### LINKED ISSUE #414: Change "semi expected" to "semicolon expected"
One of the parser errors is the expectation of a semicolon that wasn't found. To the user, this error message is "`semi expected`", which I would argue is less clearer than "`semicolon expected`". The parser error message is found in this line:

https://github.com/dafny-lang/dafny/blob/cc0b23ced11ee65d545728b05a5013fa58330c13/Source/Dafny/Parser.cs#L5773

If this is a desired change, I can submit a pull request addressing this.

### PR DESCRIPTION
**Pull request by glhrmv**
Closes #414.

### CODE REVIEW

**Comment by glhrmv** [comment]
Do I need to change `_semi` in lines 428 and 467 in`Dafny.atg` to `_semicolon`?

**Comment by mschlaipfer** [comment]
Great! Could you please update the tests as well? https://github.com/dafny-lang/dafny/blob/master/Test/exceptions/ParseErrors.dfy.expect

Currently Travis doesn't run the whole test suite unfortunately, but I assume that is the only issue. If you want to run the test suite yourself you can do so by running lit (https://github.com/dafny-lang/dafny/wiki/Running-Dafny's-test-suite).

**Comment by glhrmv** [comment]
Apologies, I wasn't sure if those were automatically generated or not. I believe everything is all set.

**Comment by RustanLeino** [comment]
Thank you!

**Pull request merged**
