### PR TITLE
docs: mark up keywords `requires` and `ensures` as inline code in prose of "Getting Started with Dafny: A Guide"

### PR DESCRIPTION
**Pull request by das-g**
Mark up keywords `requires` and `ensures` as inline code (by delimiting them by `` ` ``s, so that they appear in monospace and with different background) where they occur in prose of ["Getting Started with Dafny: A Guide"](https://dafny.org/latest/OnlineTutorial/guide).
This should make the affected sentences easier to understand, as these keywords can also occur as normal parts of speech.

### Description

- Docs-only change. (Thus user-visible, but only in the documentation.)

- I assume https://dafny.org/latest/OnlineTutorial/guide is rendered from the `master` branch. If it's instead rendered from the latest release and/or additionally rendered for releases, backporting this to those releases and releasing the result in patch releases (probably together with other changes) should probably be considered, but isn't urgent.

### How has this been tested?

I didn't test this change, beyond viewing it in VSCodium's Markdown rendering preview (which might assume a different Markdown dialect). However I'm confident that this change should work in all Markdown dialects.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Review by fabiomadge — DISMISSED** [review]
Good idea!

**Comment by fabiomadge** [comment]
For bigger changes, you can try running Jekyll locally, similar to how we describe it in the blog's [README](https://github.com/dafny-lang/blog/blob/main/README.md).

**Review by keyboardDrummer — APPROVED** [review]

**Comment by keyboardDrummer** [comment]
Small request, could you remove the hidden template instructions from the PR details when creating the PR? I use those details as part of the commit message and what was hidden in markdown then becomes visible in git, so I have to manually edit the commit message to remove those parts.

**Comment by keyboardDrummer** [comment]
> As that is not apparent when filling in the template while filing a PR, maybe the template should mention that?

Good idea: https://github.com/dafny-lang/dafny/pull/5953

**Pull request merged**
