### PR TITLE
C#: Add Dafny.Sequence.Subsequence()

### PR DESCRIPTION
**Pull request by lukemaurer**
Currently, s[lo..hi] is translated as s.Take(hi).Drop(lo), which is very expensive if lo is high.  This patch writes s.Subsequence(lo, hi) instead, where Subsequence is a new Sequence method.

### CODE REVIEW

**Comment by seanmcl** [comment]
Are there tests for this, or do the existing tests suffice?

**Comment by RustanLeino** [comment]
It would be nice if the compiler would peephole optimize `a[X..][..Y]` into `a[X..X+Y]` and peephole optimize `a[..Y][X..]` into `a[X..Y]`. Is that easy to do?

**Comment by lukemaurer** [comment]
> Are there tests for this, or do the existing tests suffice?

It's covered by Collections.dfy (in the Sequences() method).

**Comment by lukemaurer** [comment]
> It would be nice if the compiler would peephole optimize `a[X..][..Y]` into `a[X..X+Y]` and peephole optimize `a[..Y][X..]` into `a[X..Y]`. Is that easy to do?

The second one wouldn't be too bad (in Compiler.cs line 3153).  The first would be difficult in that we'd want to assign to a local to avoid duplicating X and IIRC there isn't a good way to declare a local variable in the middle of translating an expression.

**Pull request merged**
