### PR TITLE
Fix: Build Java integer types using valueOf

### LINKED ISSUE #1257: Test failures due to Java deprecation warnings
I'm trying to run the test suite following [wiki/INSTALL](https://github.com/dafny-lang/dafny/wiki/INSTALL) and I see the following failures, stable across reruns:

```
Failed Tests (15):
  Dafny :: comp/Arrays.dfy
  Dafny :: comp/AutoInit.dfy
  Dafny :: comp/Calls.dfy
  Dafny :: comp/Class.dfy
  Dafny :: comp/Collections.dfy
  Dafny :: comp/Extern.dfy
  Dafny :: comp/MainMethod.dfy
  Dafny :: comp/MoreAutoInit.dfy
  Dafny :: comp/NativeNumbers.dfy
  Dafny :: comp/Numbers.dfy
  Dafny :: comp/StaticMembersOfGenericTypes.dfy
  Dafny :: comp/TypeDescriptors.dfy
  Dafny :: dafny0/NonZeroInitializationCompile.dfy
  Dafny :: git-issues/git-issue-403.dfy
  Dafny :: server/counterexample_none.transcript


Testing Time: 1556.87s
  Unsupported      :    1
  Passed           : 1046
  Expectedly Failed:    3
  Failed           :   15
```

Running `lit` with `--show-all` shows that they are all caused by unexpected Java deprecation warnings, for example:
```
+/Users/fpoli/Documents/projects/dafny/Test/comp/Calls-java/FunctionValues_Compile/NT.java:12: warning: [removal] Byte(byte) in Byte has been deprecated and marked for removal
+    for (java.math.BigInteger j = lo; j.compareTo(hi) < 0; j.add(java.math.BigInteger.ONE)) { arr.add(new Byte(j.byteValue())); }
+                                                                                                      ^
+1 warning
```

Is there a recommended JDK version that should be used to run the test suite? I tried Amazon Corretto version 8, 11 and 16. With the first two the 15 tests that I reported above fail; with version 16 `make runtime` fails with an exception.

### PR DESCRIPTION
**Pull request by fpoli**
This PR fixes  #1257 by modifying the Java compiler to remove a deprecation warning that breaks some tests when using recent Java versions. I tested it on my system with openjdk version "1.8.0_282".

### CODE REVIEW

**Comment by fpoli** [comment]
(Actually, I need to get approval for this PR. I'll reopen it later.)

**Comment by fpoli** [comment]
Ready for review.

**Comment by RustanLeino** [comment]
Thanks for the contribution. Can you please add a test case? For example, you can add something to some file in `Test/comp`.

**Comment by fpoli** [comment]
One way to test this change is to run the test suite with a different Java version, as I do locally. Would it be acceptable to add such a test to the github tests?

If not, is there a way to make dafny dump the compilation to stdout, such that I can test it using a `.expect` file? The change of this PR doesn't modify the execution of the Java program, so adding a regression test is tricky.

**Comment by RustanLeino** [comment]
I'd prefer we stick with just one Java version at this time.

The `/spillTargetCode` switch can be used to output the generated target code. That can be brittle to compare, since any change to the compiler may cause some change somewhere in the generated target code.

What I had in mind was a simple test that produces the deprecation warning without your fix, and comes out clean with your fix. That way, if your fix somehow gets undone by some change in the future, we'll be able to detect the problem. In re-reading #1257, it seems there are already several places in the test suite that would serve that purpose. So, I'll accept and merge this PR. Thanks!

**Review by RustanLeino — APPROVED** [review]

**Pull request merged**
