### PR TITLE
Implement a proof-by-contradiction attribute

### LINKED ISSUE #4778: Enable finer-grained control of redundant- and contradictory-assumption warnings
### Summary

_No response_

### Background and Motivation

The `--warn-redundant-assumptions` and `--warn-contradictory-assumptions` options are useful for locating redundant and contradictory assumptions, but can generate false positives in nontrivial proofs. In some cases the proofs can be rewritten to avoid the warnings - but not always, it seems. It would be nice to be able to disable such warnings on a per-assertion (or per-declaration, or per-module) level.

Here is an excerpt from the Unicode libraries that generates contradictory-assumption warnings:
```dafny
  type CodeUnit
  type CodeUnitSeq = seq<CodeUnit>
  type MinimalWellFormedCodeUnitSeq = s: CodeUnitSeq
    | IsMinimalWellFormedCodeUnitSubsequence(s)
    witness *

  function IsMinimalWellFormedCodeUnitSubsequence(s: CodeUnitSeq): (b: bool)
    ensures b ==>
              && |s| > 0
              && forall i | 0 < i < |s| :: !IsMinimalWellFormedCodeUnitSubsequence(s[..i])
    decreases |s|

  /**
   * If minimal well-formed code unique subsequences `m1` and `m2` are prefixes of `s`, then they are equal.
   */
  lemma LemmaUniquePrefixMinimalWellFormedCodeUnitSeq(
    s: CodeUnitSeq, m1: MinimalWellFormedCodeUnitSeq, m2: MinimalWellFormedCodeUnitSeq
  )
    decreases |s|, |m1|, |m2|
    requires m1 <= s
    requires m2 <= s
    ensures m1 == m2
  {
    // Handle only the |m1| <= |m2| case explicitly
    if |m1| > |m2| {
      LemmaUniquePrefixMinimalWellFormedCodeUnitSeq(s, m2, m1);
    } else {
      assert m1 <= m2;
      assert m1 == m2 by {
        if m1 < m2 {
          // Here
          assert false by { assert m1 == m2[..|m1|]; }
        }
      }
    }
  }
```

The `assert false` near the end (labeled `// Here`) cannot be verified without the `by { ... }` portion. But the assertion within the `by { ... }` generates two warnings:

```
UnicodeEncodingForm.dfy(106,35): Error: proved using contradictory assumptions: assertion always holds
    |
106 |           assert false by { assert m1 == m2[..|m1|]; }
    |                                    ^^^^^^^^^^^^^^^^

UnicodeEncodingForm.dfy(106,41): Error: proved using contradictory assumptions: upper bound within range of sequence
    |
106 |           assert false by { assert m1 == m2[..|m1|]; }
    |                                          ^^^^^^^^^^
```

### Proposed Feature

This feature could, for example, be implemented as attributes (`{:warn_redundant_assumptions false}`, etc.) that are valid in assertions and at the declaration-/module-level.

### Alternatives

_No response_

### PR DESCRIPTION
**Pull request by atomb**
### Description

Allows a particular assertion to be marked as an intentional proof by contradiction, preventing `--warn-contradictory-assumptions` from flagging it.

Fixes #4778

### How has this been tested?

`Source/IntegrationTests/TestFiles/LitTests/LitTest/git-issues/git-issue-4778.dfy`

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

### CODE REVIEW

**Review by MikaelMayer — COMMENTED** [review]
Interesting and useful. Could you perhaps do two things:
- When you report "proved by contradictory assumptions", could you also mention this `{:contradiction}` attribute so that it's easy to discover?
- Add one more line in docs/dev/news about that new attribute
- Add a line about the documentation of this new attributes in docs/DafnyRef/Attributes.md

**Comment by keyboardDrummer** [comment]
Could you document the attribute in the help of the `--warn-contradictory-assumptions` option?

**Review by MikaelMayer — APPROVED** [review]
Looks great! This is a good answer to the problem of being able to assert intermediate steps when the hypotheses already contradict.
I note that it won't help for preconditions in lemmas though, correct?

**Comment by atomb** [comment]
> Looks great! This is a good answer to the problem of being able to assert intermediate steps when the hypotheses already contradict. I note that it won't help for preconditions in lemmas though, correct?

Are you thinking of the use case of trying to show that `A` and `B` are inconsistent using a lemma? So you'd write something like:

```
lemma L():
  requires A
  requires B
  ensures false
{}
```

If that's what you mean, then no, this PR doesn't support that use case. Perhaps it would be possible to allow the same attribute on an `ensures` clause, though, which would allow that.

**Pull request merged**
