### PR TITLE
feat: allow more PropagateFailure... members (do not merge; experimental)

### PR DESCRIPTION
**Pull request by RustanLeino**
Previously, the `:-` construct would always use the method or function `PropagateFailure()`
when propagating a failure. Now, a type can provide several propagate-failure members with
different result types. This makes it possible in some cases to convert between types in
failure cases.

In more detail, the extended functionality applies only to `:-` statements, not `:-` expressions.
Consider a `:-` statement whose right-hand side has type `G<X>`, where the enclosing method has
one out-parameter, say of type `H<Y>`.

This will now consider all functions and one-out-parameter methods in type `G<X>` whose name
starts with `PropagateFailure`. Consider such a propagate-failure member to be "suited" if its return
type, say `J<Z>`, has the same base-type declaration as `H<Y>`. That is, keep expanding `J<Z>`
along type synonyms and subset-type base types, yielding a type `JJ<ZZ>`, and do the same for
`H<Y>`, yielding `HH<YY>`. Then, the propagate-failure member is "suitable" if `JJ` is the same as `HH`.

If there's a unique suitable propagate-failure member, then it is picked. If there's more than one suitable
propagate-failure member, then an error is generated. If there's no suitable propagate-failure member,
then the plainly named `PropagateFailure()` is picked.

If there is no plainly named `PropagateFailure()` member, then an error is generated, even if there is
a suitable propagate-failure member.

Design note: Since Dafny does not have overloading of user-declared members, this name-prefix trick
appears useful. However, there are no other such name-prefix tricks in Dafny, so the design of this
extension is dubious. Also, the conversion has to be declared in the source type--that is, the type of
the right-hand side of the `:-`. This may not always be the best design choice. Nevertheless, in order
to experiment with ways to extend the current `:-` behavior, this change seems like a good step. It is
backward compatible, and I hope it leads to experimentation that will better inform what a more desirable
extension would be.

### CODE REVIEW

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: a0b26f0ffac9924273e2acc7d59bbc6d98e78de0
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=497f535e-f4f1-4be5-8b0b-8d0e48f3a1ae%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by samuelgruetter** [comment]
> This makes it possible in some cases to convert between types in failure cases.

Not sure if I understand what exactly becomes possible, could you please elaborate?

On thing which I see becomes possible is this: If you're writing a function returning `int`, and in its implementation, you want to use a function returning `Option<T>` for some `T`, this would previously not have been able to benefit from the `:-` notation, whereas now, you could add a `PropagateFailureInt` method returning `0` (or some other default) to `Option`.

However, I think that using the functionality added by this PR for the use case I describe above is a bad idea for the following reasons:
- Maybe a client of the function we're defining is interested in the exception, rather than just a default value potentially indistinguishable from success, so it would be better to write one function returning `Option<U>`, and a wrapper function which matches on the `Option` returned by the original function and returns a the default value in case of `None`. It's then up to the client to decide whether to use the function returning `Option` or whether to use the wrapped one with the default value.
- However, in some cases, the client is not supposed to learn that there was a failure, and should just be happy with the default value, so writing the wrapper function might look like boilerplate. But there's one important thing it achieves: It allows you to define application-specific default values, whereas the approach of of puttig the default value in a member of `Option`, that is, hardcoding it in the library, is very inflexible. Most good functional programming APIs I know don't hardcode default values in their libraries, but each function which can fail has an argument for the default value, or returns an option, or has one variant for each of the two use cases (eg Coq's `nth` vs `nth_error`, `hd` vs `hd_error`).
- Also, I would expect that it's simpler to write specifications for a potentially failing function if it returns `Option`, because it allows us to clearly distinguish between success and failure.

Not sure if what I wrote above is on point, I probably miss some context -- I'd be curious to learn more about the use cases you encountered which made you implement this feature.

**Comment by RustanLeino** [comment]
Thanks for your comments. The PR may indeed be a bad idea. Let me nevertheless expand on the context.

## Using Result for tests

Consider a situation where most methods return a `Result<T>`:

```
datatype Result<T> = Success(value: T) | Failure(error: string)
{
  predicate method IsFailure() { Failure? }
  function method Extract(): T requires Success? { value }
  function method PropagateFailure<U>(): Result<U> requires Failure? { Failure(error) }
}
```

For example:

```
predicate method ValidCommand(s: string)
method ExecuteCommand(command: string) returns (res: Result<string>)
  requires ValidCommand(command)
```

To benefit from Dafny's unit-test features, you can define a standard `Require` method like this:

```
function method Require(b: bool): Result<()> {
  if b then Success(()) else Failure("Failed requirement")
}
```

and then write a test for `ExecuteCommand` above:

```
method {:test} TestCommandExecution() returns (r: Result<()>) {
  var command := "add 2 and 5";
  var _ :- Require(ValidCommand(command));
  var res :- ExecuteCommand(command);
  var _ :- Require(res == "7");
  return Success(());
}
```

Alternatively, the last two lines of this test can be written:

```
  return Require(res == "7");
```

What's annoying about this example is that `Require` returns a `Result`, which means it needs to supply a success type. This type is not used anywhere, so the "unit" (0-tuple) type `()` is used. This means that calls to `Require` must do something with that result value, which gives rise to the occurrences of `var _` above.

## A TestResult without a success type

We may hope to improve on the situation above by introducing a different type for test results:

```
datatype TestResult = Good | Bad(error: string)
{
  predicate method IsFailure() { Bad? }
  function method PropagateFailure(): TestResult requires Bad? { this }
}

function method Require(b: bool): TestResult {
  if b then Good else Bad("Failed requirement")
}
```

This type omits the `Extract()` member, which means that you use `:-` by writing `:- Require(...)` without a left-hand side (an existing feature of `:-`). This eliminates the need for `var _` in the unit-test method above. Unfortunately, it means we can't use `:-` for the call to the method under test. Instead, the unit-test method takes the following rather clumsy form:

```
method {:test} TestCommandExecution() returns (r: TestResult) {
  var command := "add 2 and 5";
  :- Require(ValidCommand(command));
  var res := ExecuteCommand(command);
  if res.Failure? { return Bad(res.error); }
  :- Require(res.value == "7");
  return Good;
}
```

Note that a separate conversion function from `Result` to `TestResult` would not help here.

## PropagateFailure... members

This PR improves on the example given here. To benefit, you have to make `Result` aware of the type `TestResult`, like this:

```
datatype Result<T> = Success(value: T) | Failure(error: string)
{
  // IsFailure(), Extract(), and PropagateFailure() like before
  function method PropagateFailureTest(): TestResult requires Failure? { Bad(error) }
}
```

Now, the unit-test method can be written like this:

```
method {:test} TestCommandExecution() returns (r: TestResult) {
  var command := "add 2 and 5";
  :- Require(ValidCommand(command));
  var res :- ExecuteCommand(command);
  :- Require(res == "7");
  return Good;
}
```

## Conclusion

The PR makes unit tests like this look a lot better. Is that worth it? Is there a better way to make the unit-test method look good?

**Comment by samuelgruetter** [comment]
Thanks @RustanLeino for the context :+1:

I now understand the motivation better, but I'm still not sure if these conversions should be members of `TestResult` and `Result`: Suppose these two classes come from two different libraries you can't change, and your unit test (or any other piece of software you're writing) has to combine the two. Then you're stuck, because you'd have to modify at least one of them.

So in that case, I'd define a conversion function

```
function method ResultToTestResult<T>(r: Result<T>): TestResult {
  if r.Failure? then Bad("failed") else Good
}
```

and then write the unit-test method as follows:

```
method {:test} TestCommandExecution() returns (r: TestResult) {
  var command := "add 2 and 5";
  :- ResultToTestResult(Require(ValidCommand(command)));
  var tmp := ExecuteCommand(command);
  if tmp.Failure? {
    return ResultToTestResult(tmp);
  }
  var res := tmp.Extract();
  :- ResultToTestResult(Require(res == "7"));
  return Good;
}
```

Note that I had to manually desugar the `:-` for `var res :- ExecuteCommand(command);`, because we only need the `ResultToTestResult` conversion in the failure case, so the resulting code is still a bit verbose.

So how should we make this more concise? Instead of PropagateFailure... members, I'd suggest a more general feature: Implicit conversions (similar to how they're done in Scala or Coq), ie functions of type `A -> B` marked as implicit conversions which are automatically inserted whenever an expression of type `A` is found in a place where `B` is expected. Are there any plans to add implicit conversions to Dafny?

This would enable unit tests as nice as what you'd achieve with PropagateFailure... members, even if you can't add more methods to the definitions of `Result` and `TestResult`.

**Comment by RustanLeino** [comment]
Well, it was an experiment. Since it wasn't a clear winner, and since the new `expect` statement (https://github.com/dafny-lang/dafny/issues/547, https://github.com/dafny-lang/dafny/pull/550) solves some problems that the present PR attempted to solve in a different way, it is time to Close this PR.

**Pull request closed without merging**
