### PR TITLE
Compute the full path to the compiled C++ executable

### LINKED ISSUE #1100: Compile and run with C++ crashes from other directory
Using `/compile:3 /compileTarget:cpp` to compile and run a file in a different directory causes Dafny to crash.

Repro:  From the `Test/dafny4` folder in the Dafny distribution, do:

```
DAFNY/Test/dafny4$  dafny ../c++/arrays.dfy /compile:3 /compileTarget:cpp

Dafny program verifier finished with 9 verified, 0 errors
Wrote textual form of target program to arrays.cpp
Additional target code written to arrays.h
Running...

Unhandled exception. System.ComponentModel.Win32Exception (2): No such file or directory
   at System.Diagnostics.Process.ForkAndExecProcess(String filename, String[] argv, String[] envp, String cwd, Boolean redirectStdin, Boolean redirectStdout, Boolean redirectStderr, Boolean setCredentials, UInt32 userId, UInt32 groupId, UInt32[] groups, Int32& stdinFd, Int32& stdoutFd, Int32& stderrFd, Boolean usesTerminal, Boolean throwOnNoExec)
   at System.Diagnostics.Process.StartCore(ProcessStartInfo startInfo)
   at System.Diagnostics.Process.Start()
   at System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   at Microsoft.Dafny.CppCompiler.RunTargetProgram(String dafnyProgramName, String targetProgramText, String callToMain, String targetFilename, ReadOnlyCollection`1 otherFileNames, Object compilationResult, TextWriter outputWriter) in DAFNY/Source/Dafny/Compiler-cpp.cs:line 2382
   at Microsoft.Dafny.DafnyDriver.CompileDafnyProgram(Program dafnyProgram, String dafnyProgramName, ReadOnlyCollection`1 otherFileNames, Boolean invokeCompiler, TextWriter outputWriter) in DAFNY/Source/DafnyDriver/DafnyDriver.cs:line 714
   at Microsoft.Dafny.DafnyDriver.Compile(String fileName, ReadOnlyCollection`1 otherFileNames, Program dafnyProgram, PipelineOutcome oc, Dictionary`2 statss, Boolean verified) in DAFNY/Source/DafnyDriver/DafnyDriver.cs:line 436
   at Microsoft.Dafny.DafnyDriver.ProcessFiles(IList`1 dafnyFiles, ReadOnlyCollection`1 otherFileNames, ErrorReporter reporter, Boolean lookForSnapshots, String programId) in DAFNY/Source/DafnyDriver/DafnyDriver.cs:line 278
   at Microsoft.Dafny.DafnyDriver.ThreadMain(String[] args) in DAFNY/Source/DafnyDriver/DafnyDriver.cs:line 60
   at Microsoft.Dafny.DafnyDriver.<>c__DisplayClass1_0.<Main>b__0() in DAFNY/Source/DafnyDriver/DafnyDriver.cs:line 36
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

```

Changing the compile target to one of the other 4 compilers works.

### PR DESCRIPTION
**Pull request by parno**
Closes #1100.

### CODE REVIEW

**Review by RustanLeino — CHANGES_REQUESTED** [review]
Can you please add a test as well? I suggest a file `Test/git-issues/git-issue-1100.dfy` with a `lit` command to run `dafny ../c++/arrays.dfy /compile:3 /compileTarget:cpp`.

**Comment by parno** [comment]
Good point.  Just added a test.

**Review by RustanLeino — APPROVED** [review]

**Comment by RustanLeino** [comment]
The new test is failing on CI, see "ubuntu-16.04, 1" runner. (The other CI failures seem to stem from overloading the github api with too many requests in an hour. They'll probably go away after we try again.)

**Comment by parno** [comment]
Indeed.  I think the problem is that it's not finding the [`variant` standard library](https://en.cppreference.com/w/cpp/header/variant), which the C++ runtime [depends on](https://github.com/dafny-lang/dafny/blob/master/Binaries/DafnyRuntime.h#L14).  Is it possible the Ubuntu image is using an old version of C++?  More generally, is there a way to spin up the Linux container and poke around inside to debug issues like this?

**Comment by RustanLeino** [comment]
Oh, I see, the `variant` library. (I had the same problem in https://github.com/dafny-lang/dafny/pull/1073, where I sheepishly removed the otherwise passing tests for C++.)

I don't know a way to debug directly in the Linux container. What we've done in the past is trial-and-error on the CI scripts in `.github/workflows`. I suppose what's needed there is a line that installs the `variant` library.

**Comment by parno** [comment]
Okay, I'll find some time in the next couple of days to poke at it and see if I can get it into better shape.

**Comment by parno** [comment]
@RustanLeino I edited the workflow script (on this branch) so that Ubuntu-16.04 defaults to using a newer version of `g++` (namely v9), so now the new test `git-issues-1100.dfy` passes on Ubuntu.  There are still some failures on the Mac builds, but they're the result of rate limiting on fetching the Mac version of Z3.

Once these changes are merged, hopefully we can restore the tests that were removed in #1073.

**Comment by parno** [comment]
It looks like we're down to three Mac tests that are failing due to rate limiting.  Can we go ahead and merge this in anyway, since it doesn't interact with the Mac side of things?

**Review by RustanLeino — APPROVED** [review]

**Comment by RustanLeino** [comment]
Ugh. I thought I had seen all the Mac tests succeeding separately, so I had merged this into master. But it seems I was wrong, because `macos-latest, 1` is failing for real, see https://github.com/dafny-lang/dafny/pull/1125/checks?check_run_id=1948386727.

The error, which I also get locally on my Mac, is

```
warning: unknown warning option '-Wno-deprecated-copy'; did you mean '-Wno-deprecated'? [-Wunknown-warning-option]
```

**Pull request merged**
