### PR TITLE
fix: Fix naming of formals in Translator and standardize Z3 path

### LINKED ISSUE #2263: Dafny translates a file from the standard library to a syntacticly invalid Boogie code
Version of Dafny (current HEAD): `92736033599c34dc3c5cd9f0f46e3dccbd5a3210`
Version of Standard Library (also current HEAD): `44f5891e7b5b21a5f13f139b22fb5559b46de36f`

How to reproduce:

1. Generate Boogie code (note that Dafny successfully verifies the file): `dotnet dafny-head/Binaries/Dafny.dll libraries/src/Collections/Sequences/Seq.dfy /print:Seq.bpl /compile:0`

1. Attempt to verify generated code with Boogie 3.15 (version currently used by Dafny): `dotnet boogie-2.15.0/Source/BoogieDriver/bin/Debug/net6.0/BoogieDriver.dll /infer:j /proverOpt:O:auto_config=false /proverOpt:O:type_check=true /proverOpt:O:smt.case_split=3 /proverOpt:O:smt.qi.eager_threshold=100 /proverOpt:O:smt.delay_units=true /proverOpt:O:smt.arith.solver=2 Seq.bpl`

Error message:

```
Seq.bpl(20222,43): error: the type of the last parameter is unspecified
1 parse errors detected in Seq.bpl
```

Here is the line mentioned in the error message: 
`function Reads1#Handle(#$T0: Ty, #$R: Ty, HandleType) : HandleType;`

### PR DESCRIPTION
**Pull request by Dargones**
This is a new version of #2266 with changes that should make it pass all tests, both on the PR stage and during the nightly build. The reason #2266 failed during nightly build was that path to Z3 used to be different for different operation systems and modes of testing. This PR adds symbolic links that ensure there is a path to Z3 applicable to all cases. 

More specifically, right now Z3 resides at `dafny/Binaries/z3/bin/z3` if testing on Ubuntu outside the nightly build (see [here](https://github.com/dafny-lang/dafny/blob/0d78ab50330d64dd769b674cd0125a9ffc994b20/.github/workflows/integration-tests-reusable.yml#L114-L120)), at `unzippedRelease/dafny/z3/bin/z3` if testing on Ubuntu/MacOS during the nightly build (see [here](https://github.com/dafny-lang/dafny/blob/0d78ab50330d64dd769b674cd0125a9ffc994b20/.github/workflows/integration-tests-reusable.yml#L111-L113)) and at `unzippedRelease/dafny/z3/bin/z3.exe` when testing on Windows ([here](https://github.com/dafny-lang/dafny/blob/0d78ab50330d64dd769b674cd0125a9ffc994b20/.github/workflows/integration-tests-reusable.yml#L107-L110)). This PR modifies the [workflow file](https://github.com/dafny-lang/dafny/blob/master/.github/workflows/integration-tests-reusable.yml) to have symbolic links to ensure that `unzippedRelease\dafny\z3\bin\z3` always points to Z3, whatever the operations system and testing strategy. 

Aside from the Z3 path this PR is identical to #2266 and fixes #2263.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Comment by Dargones** [comment]
@robin-aws @atomb could you label this as `run-deep-tests` to make sure it works as expected on a nightly build? Perhaps it will also require me to make a dummy commit after that? Apologies about the confusion the previous PR caused with the nightly build - hope this one will fix those issues.

**Comment by atomb** [comment]
IIUC, it may be necessary to add the `run-deep-tests` label during PR creation, before the first job runs.

**Comment by Dargones** [comment]
It seems that making a dummy commit after assigning the label worked and triggered the nightly tests, thank you @atomb (I don't think I can assign labels myself)!

**Comment by davidcok** [comment]
I took Mac out of the for-the-moment-stable version of the script because it can't find OutputCheck and we wern't running it before anyway. You are using a slightly outdated commit.

**Comment by Dargones** [comment]
Thank you, @davidcok. I merged with main but I think https://github.com/dafny-lang/dafny/pull/3542 might be failing the nightly build for windows (see tests above).

**Review by atomb — APPROVED** [review]
If this passes the deep tests, let's merge it!

**Pull request merged**
