### PR TITLE
Update package.py to enable building a .NET Core release

### PR DESCRIPTION
**Pull request by keyboardDrummer**
This changes package.py so it uses `dotnet publish` to create Dafny releases for different platforms. See [this link](https://docs.microsoft.com/en-us/dotnet/core/tools/dotnet-publish) for more information on dotnet publish. The command can be used with the `-r` option to create executables for a specific os and architecture.

### Notes
- We should run `package.py` on the build server and run tests against the resulting artefact so we don't break the release process again. Could it be an option to switch all tests that use the Dafny executable  built into the Binaries folder to instead use a Dafny executable created by `dotnet publish`? That way we don't increase the integration test time and we test the release process extensively. 

- What is the current test process used for releases?

- The package currently creates a "self contained" executable which doesn't require the dotnet framework to be installed on the host machine to run it. More information can be found [here](https://docs.microsoft.com/en-us/dotnet/core/deploying/). Self contained executables are the default when creating a platform specific dotnet executable, but this can be overriden with `--self-contained false` to reduce the executable size. The self contained executable zip files are smaller than those from Dafny 2.3.0 so I guess it's fine.

- `dotnet publish` can create single file executables in which all dependencies are packaged, which I think is nicer because it hides implementation details and prevents breaking your Dafny installation by manipulating files in the Dafny folder. This PR does not use that option since it prevents sharing dependencies between Dafny and DafnyServer and that would increase the size of the resulting .zip file. Follow-up steps could be:
  - Release Dafny and DafnyServer as separate artefacts. I would prefer this option.
  - Combine the features of both in a single executable by letting Dafny.exe have a server mode activated through a command line option.

- I would prefer to consume Z3 through NuGet, so we don't need to download it or include it in the Binaries folder, but for that we need to consume it as a library instead of as an executable. I guess enabling that would require some Boogie changes.

- I think we should reference everything Dafny needs to run in the .csproj files so we can simplify `package.py`. This would include `DafnyPrelude.bpl` and the runtimes for the different languages. Ideally `dotnet publish` creates a working release without any script around it and we have no dependencies on Python or Make for the release process. I think this would mean we trigger have to trigger a call to build the Dafny JVM runtime from a .csproj file, and then it would probably be better to have a dedicated .csproj for the JVM back-end.

- `package.py` includes code to bundle `DafnyRef.pdf` into the release zip file, but I don't see this file in the existing releases such as [2.3.0](https://github.com/dafny-lang/dafny/releases/download/v2.3.0/dafny-2.3.0.10506-x64-win.zip). Is that part of `package.py` broken? My preference would be to include DafnyRef.pdf as a separate asset in a Dafny release on GitHub, instead of bundling it with a .zip that contains the executable.

- The `Binaries/libhostpolicy.dylib` file has been removed since it's created by `dotnet publish` as well.

### Testing
- Verified that on Windows the generated Dafny.exe runs and can find z3.
- Testing on other platforms has not been done
- No test suite has been ran against Dafny or DafnyServer

### CODE REVIEW

**Comment by RustanLeino** [comment]
Wonderful! Thank you.

I like the idea of doing the `dotnet publish` as part of our check-in tests and then using that version to run the test suite.

To date, we haven't had much of a test process for releases, other than that the sources always pass the test suite. This has meant that releasing a new binary has been a nerve-racking event.

**Comment by davidcok** [comment]
Remy, Thanks for the detailed notes. Here are comments:

1) I have scripts that push artifacts as a GitHub (draft) release, and then there are CI actions that pull them down into GitHub VMs and make sure they run, just with simple smoke test examples that use Boogie and Z3. That is all in a PR 835 that is waiting for this one.

2) The release process is documented in dafny/RELEASE.txt. Part of my goal is to automate it even more than it is.

3) I'm glad to hear about self-contained executables. I'll adjust the download test process accordingly.

4) OK - future work or at least for future consideration

5) (Z3) - I would rather we keep Z3 packaged with the executable at least until we move to a current Z3. It helps improve the out-of-the-box install procedure when there is less installation for a new user to do.

6) I'm happy to follow your lead on using csproj files -- I'm new to .NET

7) I will fix up DafnyRef.pdf. It is available from the Dafny website. Snapshots are saved in git, but that is a recent addition and you may not have seen it in your workspace. And yes, it was omitted inadvertently from 2.3.0 as was DafnyRuntime.jar

8) Great.

**Review by davidcok — APPROVED** [review]

**Comment by keyboardDrummer** [comment]
> I like the idea of doing the `dotnet publish` as part of our check-in tests and then using that version to run the test suite.

Have a look at this then: https://github.com/dafny-lang/dafny/pull/998

**Comment by keyboardDrummer** [comment]
> Remy, Thanks for the detailed notes. Here are comments:
> 
> 1. I have scripts that push artifacts as a GitHub (draft) release, and then there are CI actions that pull them down into GitHub VMs and make sure they run, just with simple smoke test examples that use Boogie and Z3. That is all in a PR 835 that is waiting for this one.
> 2. The release process is documented in dafny/RELEASE.txt. Part of my goal is to automate it even more than it is.
> 3. I'm glad to hear about self-contained executables. I'll adjust the download test process accordingly.
> 4. OK - future work or at least for future consideration
> 5. (Z3) - I would rather we keep Z3 packaged with the executable at least until we move to a current Z3. It helps improve the out-of-the-box install procedure when there is less installation for a new user to do.
> 6. I'm happy to follow your lead on using csproj files -- I'm new to .NET
> 7. I will fix up DafnyRef.pdf. It is available from the Dafny website. Snapshots are saved in git, but that is a recent addition and you may not have seen it in your workspace. And yes, it was omitted inadvertently from 2.3.0 as was DafnyRuntime.jar
> 8. Great.

Regarding Z3, my suggestion was not to remove Z3 from the release package. My suggestion was to reference [the Z3 NuGet package](https://www.nuget.org/packages/Microsoft.Z3.x64/), which would remove all need for any person or script to download Z3 since that would be done automatically by `dotnet` when building Dafny, and it would automatically be included in the Dafny release. The Z3 NuGet package bundles builds of the underlying native library for all platforms Z3 supports so we would also no longer need to worry about Z3 and platform compatibility.

However, the Z3 NuGet package exposes a C# interface while Boogie's [SMTLib](https://github.com/boogie-org/boogie/tree/master/Source/Provers/SMTLib) consumes Z3 through a textual protocol. I looked into adapting SMTLib so it can also consume the Z3 .NET API but I didn't make much progress.

**Pull request merged**
