### PR TITLE
Add compilation target for PHP

### PR DESCRIPTION
**Pull request by scottarc**
This PR adds a compilation target (with an enum value of `16`), but does not define a `Compiler-php.cs` file. That will follow shortly.

### CODE REVIEW

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: a00418f44b600fab3aacf9bc9f257138e94378ff
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=40f03df4-3bbc-44fc-9893-ed8895d8b7ac%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by scottarc** [comment]
> `
******************** TEST 'Dafny :: server/git-issue223.transcript' FAILED ********************`

Very interesting...

**Comment by robin-aws** [comment]
> > ` ******************** TEST 'Dafny :: server/git-issue223.transcript' FAILED ********************`
> 
> Very interesting...

This seems to be a regression in master that only shows up in CodeBuild AFAICT, likely introduced by #459. I'm looking into it now.

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 587b318d1c28582d9eddedf0ac8723b223ab5200
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=8c3333f9-72e5-491f-b16c-b2af635e0c5f%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Pull request merged**
