### PR TITLE
fix(translator): Strip type constraints before generating rank axioms

### PR DESCRIPTION
**Pull request by cpitclaudel**
Fixes GH-1875.

CC @emina. Marking as draft because it needs a thorough review, which I haven't had time to perform yet.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
The code was changed to keep constraints by @RustanLeino in 2cb43b1dd39a0c96616fe526bef646f8af95b2f9; then the comment was added also by @RustanLeino in 4fa42e674e868c62364f1258a7311429040e48ee

**Review by RustanLeino — DISMISSED** [review]
The change looks good to me.

**Comment by emina** [comment]
Thank you!

**Comment by cpitclaudel** [comment]
OK, ready for merging, I think.  There was another instance of this bug introduced by the original refactoring, but it was already fixed in ae7c504a.  I have added a test.

**Review by RustanLeino — APPROVED** [review]

**Comment by cpitclaudel** [comment]
## Additional details for 3.6 release

Due to commit [f3aabc6e](https://github.com/dafny-lang/dafny/commit/f3aabc6e01eed42a4953217df7be49b2725ea47b) (pull request [GH-1876](https://github.com/dafny-lang/dafny/pull/1876)), users migrating to Dafny 3.6 may observe changes in the identifiers names that Dafny uses in generated Boogie files.

### Context

Dafny supports `{:extern}` attributes on most declarations.  These attributes are intended to facilitate interoperation between Dafny and native code.  Concretely, adding `{:extern "Noo.dle"}` on a declaration `function Ramen()` causes Dafny to refer to the function `Ramen` as `Noo.dle()` in generated code.  These `:extern` names are only intended to be used for compilation.

### Description of the changes

Before [GH-1876](https://github.com/dafny-lang/dafny/pull/1876), Dafny also incorrectly used `{:extern}` names when generating *Boogie* files.  Here is an example of a faulty input.  

```dafny
module {:extern "External.Module.Name"} Internal.Module.Name {
  class {:extern "ExternalClassName"} InternalClassName {
    static method {:extern "ExternalMethodName"} InternalMethodName() {
      assert 1+1 == 2;
    }
  }

  class {:extern "External.Module.Name", "ExternalClassName1"} InternalClassName1 {
    static method {:extern "ExternalMethodName1"} InternalMethodName1() {
      assert 1+1 == 2;
    }
  }
}

module NoExternal.Module.Name {
  class NoExternalClassName {
    static method NoExternalMethodName() {
      assert 1+1 == 2;
    }
  }
}
```

This example has two modules.  

- Dafny 3.5 with `/print:old.bpl` generates two Boogie files named `old_External.Module.Name.bpl` and `old_NoExternal_mModule_mName.bpl`.  The first file incorrectly uses the `:extern` name and has no escaping applied to it.

- Dafny 3.6 with `/print:new.bpl` generates two Boogie files named `new_Internal_mModule_mName.bpl` and `new_NoExternal_mModule_mName.bpl`.  These files have consistent names and the `:extern` name is not used.

Comparing the generated code in both cases reveal similar changes throughout the first file, which corresponds to the `:extern` name case, since Dafny 3.6 does not use `:extern` names in Boogie files anymore:

```diff
--- old_External.Module.Name.bpl	2022-05-04 22:01:05.742643100 -0700
+++ new_Internal_mModule_mName.bpl	2022-05-04 22:01:06.523768000 -0700
@@ -1,5 +1,5 @@
 // Dafny 3.5.0.40314
-// Command Line Options: -print:old.bpl -noVerify extern.dfy
+// Command Line Options: -print:new.bpl -noVerify extern.dfy
 
 type Ty;
 
@@ -2761,44 +2772,44 @@
 
 const unique class._System.Tuple0: ClassName;
 
-const unique class.External.Module.Name.ExternalClassName?: ClassName;
+const unique class.Internal_mModule_mName.InternalClassName?: ClassName;
 
-function Tclass.External.Module.Name.ExternalClassName?() : Ty;
+function Tclass.Internal_mModule_mName.InternalClassName?() : Ty;
 
-const unique Tagclass.External.Module.Name.ExternalClassName?: TyTag;
+const unique Tagclass.Internal_mModule_mName.InternalClassName?: TyTag;
 
-// Tclass.External.Module.Name.ExternalClassName? Tag
-axiom Tag(Tclass.External.Module.Name.ExternalClassName?())
-     == Tagclass.External.Module.Name.ExternalClassName?
-   && TagFamily(Tclass.External.Module.Name.ExternalClassName?())
+// Tclass.Internal_mModule_mName.InternalClassName? Tag
+axiom Tag(Tclass.Internal_mModule_mName.InternalClassName?())
+     == Tagclass.Internal_mModule_mName.InternalClassName?
+   && TagFamily(Tclass.Internal_mModule_mName.InternalClassName?())
      == tytagFamily$InternalClassName;
 
-// Box/unbox axiom for Tclass.External.Module.Name.ExternalClassName?
+// Box/unbox axiom for Tclass.Internal_mModule_mName.InternalClassName?
 axiom (forall bx: Box :: 
-  { $IsBox(bx, Tclass.External.Module.Name.ExternalClassName?()) } 
-  $IsBox(bx, Tclass.External.Module.Name.ExternalClassName?())
+  { $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName?()) } 
+  $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName?())
      ==> $Box($Unbox(bx): ref) == bx
-       && $Is($Unbox(bx): ref, Tclass.External.Module.Name.ExternalClassName?()));
+       && $Is($Unbox(bx): ref, Tclass.Internal_mModule_mName.InternalClassName?()));
 
 // InternalClassName: Class $Is
 axiom (forall $o: ref :: 
-  { $Is($o, Tclass.External.Module.Name.ExternalClassName?()) } 
-  $Is($o, Tclass.External.Module.Name.ExternalClassName?())
-     <==> $o == null || dtype($o) == Tclass.External.Module.Name.ExternalClassName?());
+  { $Is($o, Tclass.Internal_mModule_mName.InternalClassName?()) } 
+  $Is($o, Tclass.Internal_mModule_mName.InternalClassName?())
+     <==> $o == null || dtype($o) == Tclass.Internal_mModule_mName.InternalClassName?());
 
 // InternalClassName: Class $IsAlloc
 axiom (forall $o: ref, $h: Heap :: 
-  { $IsAlloc($o, Tclass.External.Module.Name.ExternalClassName?(), $h) } 
-  $IsAlloc($o, Tclass.External.Module.Name.ExternalClassName?(), $h)
+  { $IsAlloc($o, Tclass.Internal_mModule_mName.InternalClassName?(), $h) } 
+  $IsAlloc($o, Tclass.Internal_mModule_mName.InternalClassName?(), $h)
      <==> $o == null || read($h, $o, alloc));
 
-procedure {:extern "ExternalMethodName"} CheckWellformed$$External.Module.Name.ExternalClassName.ExternalMethodName();
+procedure {:extern "ExternalMethodName"} CheckWellformed$$Internal_mModule_mName.InternalClassName.InternalMethodName();
   free requires 1 == $FunctionContextHeight;
   modifies $Heap, $Tick;
 
 
 
-procedure {:extern "ExternalMethodName"} Call$$External.Module.Name.ExternalClassName.ExternalMethodName();
+procedure {:extern "ExternalMethodName"} Call$$Internal_mModule_mName.InternalClassName.InternalMethodName();
   modifies $Heap, $Tick;
   // frame condition: object granularity
   free ensures (forall $o: ref :: 
@@ -2809,7 +2820,7 @@
 
 
 
-procedure {:extern "ExternalMethodName"} Impl$$External.Module.Name.ExternalClassName.ExternalMethodName() returns ($_reverifyPost: bool);
+procedure {:extern "ExternalMethodName"} Impl$$Internal_mModule_mName.InternalClassName.InternalMethodName() returns ($_reverifyPost: bool);
   free requires 1 == $FunctionContextHeight;
   modifies $Heap, $Tick;
   // frame condition: object granularity
@@ -2821,11 +2832,11 @@
 
 
 
-implementation {:extern "ExternalMethodName"} Impl$$External.Module.Name.ExternalClassName.ExternalMethodName() returns ($_reverifyPost: bool)
+implementation {:extern "ExternalMethodName"} Impl$$Internal_mModule_mName.InternalClassName.InternalMethodName() returns ($_reverifyPost: bool)
 {
   var $_Frame: <beta>[ref,Field beta]bool;
 
-    // AddMethodImpl: InternalMethodName, Impl$$External.Module.Name.ExternalClassName.ExternalMethodName
+    // AddMethodImpl: InternalMethodName, Impl$$Internal_mModule_mName.InternalClassName.InternalMethodName
     $_Frame := (lambda<alpha> $o: ref, $f: Field alpha :: 
       $o != null && read($Heap, $o, alloc) ==> false);
     $_reverifyPost := false;
@@ -2836,73 +2847,73 @@
 
 
 
-function Tclass.External.Module.Name.InternalClassName() : Ty;
+function Tclass.Internal_mModule_mName.InternalClassName() : Ty;
 
-const unique Tagclass.External.Module.Name.InternalClassName: TyTag;
+const unique Tagclass.Internal_mModule_mName.InternalClassName: TyTag;
 
-// Tclass.External.Module.Name.InternalClassName Tag
-axiom Tag(Tclass.External.Module.Name.InternalClassName())
-     == Tagclass.External.Module.Name.InternalClassName
-   && TagFamily(Tclass.External.Module.Name.InternalClassName())
+// Tclass.Internal_mModule_mName.InternalClassName Tag
+axiom Tag(Tclass.Internal_mModule_mName.InternalClassName())
+     == Tagclass.Internal_mModule_mName.InternalClassName
+   && TagFamily(Tclass.Internal_mModule_mName.InternalClassName())
      == tytagFamily$InternalClassName;
 
-// Box/unbox axiom for Tclass.External.Module.Name.InternalClassName
+// Box/unbox axiom for Tclass.Internal_mModule_mName.InternalClassName
 axiom (forall bx: Box :: 
-  { $IsBox(bx, Tclass.External.Module.Name.InternalClassName()) } 
-  $IsBox(bx, Tclass.External.Module.Name.InternalClassName())
+  { $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName()) } 
+  $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName())
      ==> $Box($Unbox(bx): ref) == bx
-       && $Is($Unbox(bx): ref, Tclass.External.Module.Name.InternalClassName()));
+       && $Is($Unbox(bx): ref, Tclass.Internal_mModule_mName.InternalClassName()));
 
 // Internal.Module.Name.InternalClassName: non-null type $Is
 axiom (forall c#0: ref :: 
-  { $Is(c#0, Tclass.External.Module.Name.InternalClassName()) } 
-  $Is(c#0, Tclass.External.Module.Name.InternalClassName())
-     <==> $Is(c#0, Tclass.External.Module.Name.ExternalClassName?()) && c#0 != null);
+  { $Is(c#0, Tclass.Internal_mModule_mName.InternalClassName()) } 
+  $Is(c#0, Tclass.Internal_mModule_mName.InternalClassName())
+     <==> $Is(c#0, Tclass.Internal_mModule_mName.InternalClassName?()) && c#0 != null);
 
 // Internal.Module.Name.InternalClassName: non-null type $IsAlloc
 axiom (forall c#0: ref, $h: Heap :: 
-  { $IsAlloc(c#0, Tclass.External.Module.Name.InternalClassName(), $h) } 
-  $IsAlloc(c#0, Tclass.External.Module.Name.InternalClassName(), $h)
-     <==> $IsAlloc(c#0, Tclass.External.Module.Name.ExternalClassName?(), $h));
+  { $IsAlloc(c#0, Tclass.Internal_mModule_mName.InternalClassName(), $h) } 
+  $IsAlloc(c#0, Tclass.Internal_mModule_mName.InternalClassName(), $h)
+     <==> $IsAlloc(c#0, Tclass.Internal_mModule_mName.InternalClassName?(), $h));
 
-const unique class.External.Module.Name.ExternalClassName1?: ClassName;
+const unique class.Internal_mModule_mName.InternalClassName1?: ClassName;
 
-function Tclass.External.Module.Name.ExternalClassName1?() : Ty;
+function Tclass.Internal_mModule_mName.InternalClassName1?() : Ty;
 
-const unique Tagclass.External.Module.Name.ExternalClassName1?: TyTag;
+const unique Tagclass.Internal_mModule_mName.InternalClassName1?: TyTag;
 
-// Tclass.External.Module.Name.ExternalClassName1? Tag
-axiom Tag(Tclass.External.Module.Name.ExternalClassName1?())
-     == Tagclass.External.Module.Name.ExternalClassName1?
-   && TagFamily(Tclass.External.Module.Name.ExternalClassName1?())
+// Tclass.Internal_mModule_mName.InternalClassName1? Tag
+axiom Tag(Tclass.Internal_mModule_mName.InternalClassName1?())
+     == Tagclass.Internal_mModule_mName.InternalClassName1?
+   && TagFamily(Tclass.Internal_mModule_mName.InternalClassName1?())
      == tytagFamily$InternalClassName1;
 
-// Box/unbox axiom for Tclass.External.Module.Name.ExternalClassName1?
+// Box/unbox axiom for Tclass.Internal_mModule_mName.InternalClassName1?
 axiom (forall bx: Box :: 
-  { $IsBox(bx, Tclass.External.Module.Name.ExternalClassName1?()) } 
-  $IsBox(bx, Tclass.External.Module.Name.ExternalClassName1?())
+  { $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName1?()) } 
+  $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName1?())
      ==> $Box($Unbox(bx): ref) == bx
-       && $Is($Unbox(bx): ref, Tclass.External.Module.Name.ExternalClassName1?()));
+       && $Is($Unbox(bx): ref, Tclass.Internal_mModule_mName.InternalClassName1?()));
 
 // InternalClassName1: Class $Is
 axiom (forall $o: ref :: 
-  { $Is($o, Tclass.External.Module.Name.ExternalClassName1?()) } 
-  $Is($o, Tclass.External.Module.Name.ExternalClassName1?())
-     <==> $o == null || dtype($o) == Tclass.External.Module.Name.ExternalClassName1?());
+  { $Is($o, Tclass.Internal_mModule_mName.InternalClassName1?()) } 
+  $Is($o, Tclass.Internal_mModule_mName.InternalClassName1?())
+     <==> $o == null || dtype($o) == Tclass.Internal_mModule_mName.InternalClassName1?());
 
 // InternalClassName1: Class $IsAlloc
 axiom (forall $o: ref, $h: Heap :: 
-  { $IsAlloc($o, Tclass.External.Module.Name.ExternalClassName1?(), $h) } 
-  $IsAlloc($o, Tclass.External.Module.Name.ExternalClassName1?(), $h)
+  { $IsAlloc($o, Tclass.Internal_mModule_mName.InternalClassName1?(), $h) } 
+  $IsAlloc($o, Tclass.Internal_mModule_mName.InternalClassName1?(), $h)
      <==> $o == null || read($h, $o, alloc));
 
-procedure {:extern "ExternalMethodName1"} CheckWellformed$$External.Module.Name.ExternalClassName1.ExternalMethodName1();
+procedure {:extern "ExternalMethodName1"} CheckWellformed$$Internal_mModule_mName.InternalClassName1.InternalMethodName1();
   free requires 1 == $FunctionContextHeight;
   modifies $Heap, $Tick;
 
 
 
-procedure {:extern "ExternalMethodName1"} Call$$External.Module.Name.ExternalClassName1.ExternalMethodName1();
+procedure {:extern "ExternalMethodName1"} Call$$Internal_mModule_mName.InternalClassName1.InternalMethodName1();
   modifies $Heap, $Tick;
   // frame condition: object granularity
   free ensures (forall $o: ref :: 
@@ -2913,7 +2924,7 @@
 
 
 
-procedure {:extern "ExternalMethodName1"} Impl$$External.Module.Name.ExternalClassName1.ExternalMethodName1() returns ($_reverifyPost: bool);
+procedure {:extern "ExternalMethodName1"} Impl$$Internal_mModule_mName.InternalClassName1.InternalMethodName1() returns ($_reverifyPost: bool);
   free requires 1 == $FunctionContextHeight;
   modifies $Heap, $Tick;
   // frame condition: object granularity
@@ -2925,11 +2936,11 @@
 
 
 
-implementation {:extern "ExternalMethodName1"} Impl$$External.Module.Name.ExternalClassName1.ExternalMethodName1() returns ($_reverifyPost: bool)
+implementation {:extern "ExternalMethodName1"} Impl$$Internal_mModule_mName.InternalClassName1.InternalMethodName1() returns ($_reverifyPost: bool)
 {
   var $_Frame: <beta>[ref,Field beta]bool;
 
-    // AddMethodImpl: InternalMethodName1, Impl$$External.Module.Name.ExternalClassName1.ExternalMethodName1
+    // AddMethodImpl: InternalMethodName1, Impl$$Internal_mModule_mName.InternalClassName1.InternalMethodName1
     $_Frame := (lambda<alpha> $o: ref, $f: Field alpha :: 
       $o != null && read($Heap, $o, alloc) ==> false);
     $_reverifyPost := false;
@@ -2940,63 +2951,63 @@
 
 
 
-function Tclass.External.Module.Name.InternalClassName1() : Ty;
+function Tclass.Internal_mModule_mName.InternalClassName1() : Ty;
 
-const unique Tagclass.External.Module.Name.InternalClassName1: TyTag;
+const unique Tagclass.Internal_mModule_mName.InternalClassName1: TyTag;
 
-// Tclass.External.Module.Name.InternalClassName1 Tag
-axiom Tag(Tclass.External.Module.Name.InternalClassName1())
-     == Tagclass.External.Module.Name.InternalClassName1
-   && TagFamily(Tclass.External.Module.Name.InternalClassName1())
+// Tclass.Internal_mModule_mName.InternalClassName1 Tag
+axiom Tag(Tclass.Internal_mModule_mName.InternalClassName1())
+     == Tagclass.Internal_mModule_mName.InternalClassName1
+   && TagFamily(Tclass.Internal_mModule_mName.InternalClassName1())
      == tytagFamily$InternalClassName1;
 
-// Box/unbox axiom for Tclass.External.Module.Name.InternalClassName1
+// Box/unbox axiom for Tclass.Internal_mModule_mName.InternalClassName1
 axiom (forall bx: Box :: 
-  { $IsBox(bx, Tclass.External.Module.Name.InternalClassName1()) } 
-  $IsBox(bx, Tclass.External.Module.Name.InternalClassName1())
+  { $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName1()) } 
+  $IsBox(bx, Tclass.Internal_mModule_mName.InternalClassName1())
      ==> $Box($Unbox(bx): ref) == bx
-       && $Is($Unbox(bx): ref, Tclass.External.Module.Name.InternalClassName1()));
+       && $Is($Unbox(bx): ref, Tclass.Internal_mModule_mName.InternalClassName1()));
 
 // Internal.Module.Name.InternalClassName1: non-null type $Is
 axiom (forall c#0: ref :: 
-  { $Is(c#0, Tclass.External.Module.Name.InternalClassName1()) } 
-  $Is(c#0, Tclass.External.Module.Name.InternalClassName1())
-     <==> $Is(c#0, Tclass.External.Module.Name.ExternalClassName1?()) && c#0 != null);
+  { $Is(c#0, Tclass.Internal_mModule_mName.InternalClassName1()) } 
+  $Is(c#0, Tclass.Internal_mModule_mName.InternalClassName1())
+     <==> $Is(c#0, Tclass.Internal_mModule_mName.InternalClassName1?()) && c#0 != null);
 
 // Internal.Module.Name.InternalClassName1: non-null type $IsAlloc
 axiom (forall c#0: ref, $h: Heap :: 
-  { $IsAlloc(c#0, Tclass.External.Module.Name.InternalClassName1(), $h) } 
-  $IsAlloc(c#0, Tclass.External.Module.Name.InternalClassName1(), $h)
-     <==> $IsAlloc(c#0, Tclass.External.Module.Name.ExternalClassName1?(), $h));
+  { $IsAlloc(c#0, Tclass.Internal_mModule_mName.InternalClassName1(), $h) } 
+  $IsAlloc(c#0, Tclass.Internal_mModule_mName.InternalClassName1(), $h)
+     <==> $IsAlloc(c#0, Tclass.Internal_mModule_mName.InternalClassName1?(), $h));
 
-const unique class.External.Module.Name.__default: ClassName;
+const unique class.Internal_mModule_mName.__default: ClassName;
 
-function Tclass.External.Module.Name.__default() : Ty;
+function Tclass.Internal_mModule_mName.__default() : Ty;
 
-const unique Tagclass.External.Module.Name.__default: TyTag;
+const unique Tagclass.Internal_mModule_mName.__default: TyTag;
 
-// Tclass.External.Module.Name.__default Tag
-axiom Tag(Tclass.External.Module.Name.__default())
-     == Tagclass.External.Module.Name.__default
-   && TagFamily(Tclass.External.Module.Name.__default()) == tytagFamily$_default;
+// Tclass.Internal_mModule_mName.__default Tag
+axiom Tag(Tclass.Internal_mModule_mName.__default())
+     == Tagclass.Internal_mModule_mName.__default
+   && TagFamily(Tclass.Internal_mModule_mName.__default()) == tytagFamily$_default;
 
-// Box/unbox axiom for Tclass.External.Module.Name.__default
+// Box/unbox axiom for Tclass.Internal_mModule_mName.__default
 axiom (forall bx: Box :: 
-  { $IsBox(bx, Tclass.External.Module.Name.__default()) } 
-  $IsBox(bx, Tclass.External.Module.Name.__default())
+  { $IsBox(bx, Tclass.Internal_mModule_mName.__default()) } 
+  $IsBox(bx, Tclass.Internal_mModule_mName.__default())
      ==> $Box($Unbox(bx): ref) == bx
-       && $Is($Unbox(bx): ref, Tclass.External.Module.Name.__default()));
+       && $Is($Unbox(bx): ref, Tclass.Internal_mModule_mName.__default()));
 
 // _default: Class $Is
 axiom (forall $o: ref :: 
-  { $Is($o, Tclass.External.Module.Name.__default()) } 
-  $Is($o, Tclass.External.Module.Name.__default())
-     <==> $o == null || dtype($o) == Tclass.External.Module.Name.__default());
+  { $Is($o, Tclass.Internal_mModule_mName.__default()) } 
+  $Is($o, Tclass.Internal_mModule_mName.__default())
+     <==> $o == null || dtype($o) == Tclass.Internal_mModule_mName.__default());
 
 // _default: Class $IsAlloc
 axiom (forall $o: ref, $h: Heap :: 
-  { $IsAlloc($o, Tclass.External.Module.Name.__default(), $h) } 
-  $IsAlloc($o, Tclass.External.Module.Name.__default(), $h)
+  { $IsAlloc($o, Tclass.Internal_mModule_mName.__default(), $h) } 
+  $IsAlloc($o, Tclass.Internal_mModule_mName.__default(), $h)
      <==> $o == null || read($h, $o, alloc));
 
 const unique tytagFamily$nat: TyTagFamily;
```

In contrast, the second file has no naming changes.

**Pull request merged**
