### PR TITLE
Print command line arguments in source attribute of generated C# code

### LINKED ISSUE #3441: "dafny translate" a bit different than "dafny compile:0 /spillTargetCode:3"
### Dafny version

3.10.0

### Code to produce this issue

```dafny
// File.dfy

method Main() {
}
```

### Command to run and resulting output

```code
dafny -out:GeneratedFromDafny.cs File.dfy -compile:0 -spillTargetCode:3 -noVerify
dafny translate cs --output GeneratedFromDafny2.cs File.dfy
diff GeneratedFromDafny.cs GeneratedFromDafny2.cs
```

### What happened?

I expected no diff, but I got:
```diff
-[assembly: DafnyAssembly.DafnySourceAttribute(@"// dafny 3.10.0.41215
-// Command Line Options: /out:GeneratedFromDafny.cs File.dfy /compile:0 /spillTargetCode:3 /noVerify
-// File.dfy
+[assembly: DafnyAssembly.DafnySourceAttribute(@"// File.dfy
```

Note that if I changed spillTargetCode from 3 to 1 in the old comamnd line, I get the new result as well which does not contain metadata.
```
dafny -out:GeneratedFromDafny.cs File.dfy -compile:0 -spillTargetCode:1 -noVerify
```

### What type of operating system are you experiencing the problem on?

Windows

### PR DESCRIPTION
**Pull request by keyboardDrummer**
Fixes #3441

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Review by davidcok — COMMENTED** [review]
Is there a test or example of this feature?

**Comment by keyboardDrummer** [comment]
> Is there a test or example of this feature?

I'm not aware of any test of the SourceAttribute that is put in the translated code. Are you?

I'm not sure how to easily add a test on purely the SourceAttribute, so it doesn't lock down exactly what C# we generate. Any ideas?

**Review by MikaelMayer — APPROVED** [review]
Looks good to me. The removal of the "var x;" and use the "var x := *" is it just for style, or there is a deprecation coming?

**Comment by keyboardDrummer** [comment]
> Looks good to me. The removal of the "var x;" and use the "var x := *" is it just for style, or there is a deprecation coming?

It prevents me from having to use the migration option `--relax-definite-assignment`. Using havocs in the way this PR does will is the recommended way of writing Dafny when using the new CLI.

**Pull request merged**
