### PR TITLE
Language Server: Add exception guard to the document loader

### PR DESCRIPTION
**Pull request by camrein**
I've added a guard to the recently introduced document loading thread. Without it, an exception will break the complete document processing of the language server. With this change, an exception is propagated to the calling request just as it was before.

Furthermore, I've updated some of the 3rd party dependencies of the language server and its test project.

### CODE REVIEW

**Review by keyboardDrummer — APPROVED** [review]
Could you add a test related to this as well? Reliability is something we need to improve and a test would really help here.

**Comment by camrein** [comment]
> 
> 
> Could you add a test related to this as well? Reliability is something we need to improve and a test would really help.

I'd love to. But the situation here is a bit difficult. Any exception that would bubble up to this catch-clause mostly denotes a bug; thus, should be fixed rather than used as a test case. However, I wanted to avoid the case where the language server becomes unresponsive if an unhandled exception occurs. So I tried to design this guard so that the exception behavior stays the same as before introducing the processing thread. We could argue that the code is unnecessary because it's only relevant in case of bugs. But I have the feeling that these will be hard to debug in the future as the exceptions will be unhandled otherwise.
Furthermore, the `OperationCanceledException` cannot happen as of now since these requests cannot be canceled yet. This feature requires the changes suggested in #1448.

**Comment by keyboardDrummer** [comment]
> > Could you add a test related to this as well? Reliability is something we need to improve and a test would really help.
> 
> I'd love to. But the situation here is a bit difficult. Any exception that would bubble up to this catch-clause mostly denotes a bug; thus, should be fixed rather than used as a test case. However, I wanted to avoid the case where the language server becomes unresponsive if an unhandled exception occurs. So I tried to design this guard so that the exception behavior stays the same as before introducing the processing thread. We could argue that the code is unnecessary because it's only relevant in case of bugs. But I have the feeling that these will be hard to debug in the future as the exceptions will be unhandled otherwise.
> Furthermore, the `OperationCanceledException` cannot happen as of now since these requests cannot be canceled yet. This feature requires the changes suggested in #1448.

Couldn't you create `TextDocumentLoader` and pass in a faulty Parser?

**Comment by camrein** [comment]
> Couldn't you create `TextDocumentLoader` and pass in a faulty Parser?

Of course. It's a bit out of place compared to all other tests. It's the first actual unit test since the others are integration tests interacting mostly through the LSP API.

**Review by keyboardDrummer — APPROVED** [review]

**Comment by keyboardDrummer** [comment]
> > Couldn't you create `TextDocumentLoader` and pass in a faulty Parser?
> 
> Of course. It's a bit out of place compared to all other tests. It's the first actual unit test since the others are integration tests interacting mostly through the LSP API (probably the reason why I didn't think of mocking before).

Thanks :)

**Pull request merged**
