### PR TITLE
Use %diff instead of diff for test

### PR DESCRIPTION
**Pull request by atomb**
Hopefully this fixes nightly tests on Windows

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Review by davidcok — APPROVED** [review]
%diff is correct, of course. Hope it fixes the nightly test problem.

**Comment by davidcok** [comment]
Did you label the PR before you started the tests?  It looks like you will need to re-trigger the tests to get the PR to a mergable state

**Comment by atomb** [comment]
> Did you label the PR before you started the tests? It looks like you will need to re-trigger the tests to get the PR to a mergable state

The tests started automatically before I had a chance to label it, and re-starting them doesn't seem to make a difference so far. Have you successfully used `run-deep-tests` before?

**Comment by fabiomadge** [comment]
You need to add the tag before pushing the commit.

**Pull request merged**
