### PR TITLE
Trigger release-downloads only on releases

### PR DESCRIPTION
**Pull request by RustanLeino**
The purpose of this change is to reduce the number of github API requests done with each Pull Request. Since github throttles such API requests, Dafny CI builds often fail. The `release-downloads.yml` tests call the github API and don’t seem necessary unless there’s a new release. Therefore, this seems like a simple fix to an annoying problem. (This change can, of course, be reverted if we authenticate the API requests—which does not count against the throttling limit—or see the need to have more frequent release tests again.)

Co-authored-by: @keyboardDrummer

### CODE REVIEW

**Comment by davidcok** [comment]
I concur that testing the release downloads on every PR merge is overkill. If I had known there was a means to trigger on just the publication of a release, I’d have done this before, so +10 from me.

**Review by keyboardDrummer — DISMISSED** [review]
LGTM

**Comment by RustanLeino** [comment]
I don't understand why so many of the builds are still failing.

**Comment by keyboardDrummer** [comment]
> I don't understand why so many of the builds are still failing.

Looks like it's because because of another GitHub API ratelimit that's being hit by a GitHub request in package.py [here](https://github.com/dafny-lang/dafny/blob/master/Scripts/package.py#L188) when it's downloading Z3.

I don't see a straightforward fix. You can reduce the size of the problem by splitting msbuild.yaml up into two jobs, as is explained here: https://github.com/actions/create-release/issues/14#issuecomment-555379810

That way the CI.zip created [here](https://github.com/dafny-lang/dafny/blob/master/.github/workflows/msbuild.yml#L75) only has to be created once and the shards can re-use it, which cuts the API rate by 5.

Another (better?) thing you can try to is to make the GitHub API calls authenticated. Apparently GitHub makes it easy to authenticate calls from inside a GitHub action, more information is [here](https://docs.github.com/en/actions/reference/authentication-in-a-workflow).

It seems like unauthenticated calls have a rate limit of 60 per hour, which would explain why we're hitting them. Authenticated calls have a rate limit of 5000 per hour so that should be ample:

From the docs: https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting
> For API requests using Basic Authentication or OAuth, you can make up to 5,000 requests per hour. Authenticated requests are associated with the authenticated user, regardless of whether Basic Authentication or an OAuth token was used. This means that all OAuth applications authorized by a user share the same quota of 5,000 requests per hour when they authenticate with different tokens owned by the same user.

> For users that belong to a GitHub Enterprise Cloud account, requests made using an OAuth token to resources owned by the same GitHub Enterprise Cloud account have an increased limit of 15,000 requests per hour.

> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

**Review by keyboardDrummer — APPROVED** [review]

**Pull request merged**
