### PR TITLE
fix: Fully-qualify module CompileNames

### PR DESCRIPTION
**Pull request by robin-aws**
This fixes issues with compiled module names being context-sensitive and inconsistent when compiled separately into DLLs. See Test/dafny0/DafnyLib.dfy and Test/comp/Module.dfy for the regression tests and more details.

### CODE REVIEW

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: fe1ee73f53aa07c8990fa73fc2f66f44bc0ea7c7
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=9d94c659-4023-41de-bdf8-eede101259a6%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 3cfaf27f23d5072e836688ab25c3748f8a4f4063
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=0d7a47f0-e680-4376-a26e-522e3adb4d50%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by RustanLeino** [comment]
The underscore is a good idea. Can you do this through `Declaration.IdProtect`? If so, we may be able to keep the `.`'s for C# and Java, while doing the `_m` for languages where `.` won't work.

**Comment by robin-aws** [comment]
> The underscore is a good idea. Can you do this through `Declaration.IdProtect`? If so, we may be able to keep the `.`'s for C# and Java, while doing the `_m` for languages where `.` won't work.

We discussed this offline, and my stance is that it's better to keep the compiler implementations simpler where possible. Trying to produce idiomatic output is a very different goal than just producing something semantically correct, and we're currently aiming for the latter. This change is still a strict improvement over the current _##_-prefixed approach anyway, and we can already improve it later.

**Pull request merged**
