### PR TITLE
Compiled functions

### PR DESCRIPTION
**Pull request by RustanLeino**
This PR introduces a proposed change of syntax from the confusing keyword phrases `function method` and `predicate method` to `compiled function` and `compiled predicate`, respectively. The PR allows both pairs of keyword phrases as synonyms, but gears up toward just accepting the `compiled ...` phrases in the future. In particular, documentation and all tests are changed to the new syntax, and the old syntax gives a deprecation warning under (the non-default) `/deprecation:2`.

In this PR, `compiled` is not a keyword by itself. It is only looked upon specially in the two new keyword phrases.

If accepted, this PR should be followed by an update of `dafny-lang/ide-vscode` to accept the new keyword, and corresponding updates in `dafny-lang/libraries`.

### CODE REVIEW

**Comment by RustanLeino** [comment]
Beyond reviewing the language change itself, I think the easiest way to review this PR is to look at each individual commit. Those commits are either boring (and huge) or interesting (and small).

**Review by robin-aws — CHANGES_REQUESTED** [review]
Just flagging that there is still some open discussion around whether we should also tweak the syntax for the `function by method` feature, since it is still arguably using the `method` keyword to indicate "when compiled", and we may want to align the concepts better.

**Review by keyboardDrummer — APPROVED** [review]

**Comment by robin-aws** [comment]
Also potentially blocked on https://github.com/dafny-lang/dafny/discussions/1564 - this PR is definitely an improvement, but we may want to consider deeper changes before making this change and then potentially undoing it shortly after.

**Comment by RustanLeino** [comment]
Given the discussion on https://github.com/dafny-lang/dafny/discussions/1564, I'm retracting this PR and hope to instead follow up with one based on that discussion.

**Pull request closed without merging**
