### PR TITLE
Java: Unboxed primitives

### PR DESCRIPTION
**Pull request by lukemaurer**
(Depends on #524.)

This would have been easy if it weren't for the unfortunate interaction between primitives, arrays, and generics in Java.  Namely, a method taking a `T[]` can't take a `byte[]`, because `T` can only stand for a reference type.  Thus the only type that can stand for an array of any type is `java.lang.Object`.  We need a fast way to create and operate on arrays of arbitrary type, and Java does not provide it (most methods of `java.lang.reflect.Array` are very slow).  This was a three-step process:

1. #523: In the base `Compiler` class, introduce a general system for turning assignments into calls to setter methods so that an assignment to an array of unknown type can be expressed as a method call.  (Java already needed this; its implementation of trait fields was buggy.)

2. #524: Replace the strings used for type descriptors with objects, which are much faster and more type-safe.  (This also fixes existing bugs.)

3. This PR: Have all primitive types appear in unboxed form where possible (that is, when the type isn't a parameter).  Represent a generic array as a `java.lang.Object` and use the corresponding `dafny.Type` for array operations.

### CODE REVIEW

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: b0c0e38c7102b80a8fb702ae9ef1d850455092ad
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b62eb35b-2faf-492f-b7c3-c83b279d452a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by seanmcl** [comment]
Could you push a branch for the `concat` change and base this on that branch?  As a reviewer I don't want to read the same changes twice.

**Comment by lukemaurer** [comment]
> Could you push a branch for the `concat` change and base this on that branch? As a reviewer I don't want to read the same changes twice.

!! Good idea, done.

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 2472afe61f99d439a6abe50d6a86b583363947a5
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=dc9e4db1-fd67-471a-9782-e180d93edc24%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 644fcc5ebc26efdb25c6626ae48d3b92ab648150
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=fa4e5f0e-3f9c-44a9-a67c-5f6c1c3efcfa%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: c65c1967ff718a866c98b721c8b6a99fb9e59cb2
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=1fb6231d-11cd-4f8a-a225-1da14831063c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: ec6a81d9ef88a0921f31cd01ffa8bf551bc8766c
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=6e3d7e03-e441-4f1c-9749-ecb6826b3892%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
Hi @lukemaurer! I'm excited to review this but it's a really large change set. Is there any chance you could break it up into 2 or even 3 different PRs in sequence, given the high-level breakdown you gave?

**Comment by lukemaurer** [comment]
> Hi @lukemaurer! I'm excited to review this but it's a really large change set. Is there any chance you could break it up into 2 or even 3 different PRs in sequence, given the high-level breakdown you gave?

I can, though it's a bit of a bumpy road in places—in particular, DafnySequence.java gets overhauled twice.  I'll try and rearrange things so there's not too much to re-review.

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: d3bb417cc409906e21fea1b8a0828f5b1ffee55d
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=d36a5b9e-4569-43ea-a202-0988fbf9850a%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 5245c1f47e97463e9ea29d6c6c90ebf1904c6098
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=e48f7c11-68dc-4a1c-a031-82dd3d430545%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by lukemaurer** [comment]
> Hi @lukemaurer! I'm excited to review this but it's a really large change set. Is there any chance you could break it up into 2 or even 3 different PRs in sequence, given the high-level breakdown you gave?

Okay, done:  There's now #521 (largely unrelated but other changes build on it), #522, #523, and #524.  Unfortunately, there's a bit of churn in DafnySequence still ...)

**Comment by robin-aws** [comment]
Thanks @lukemaurer, this is much more digestible now! :) I'll start with #521 and go from there.

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: edfe97b33e2b2df433a40f4ae33e816aef3c7601
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=08afbe8d-ed10-429a-b270-5199df6370dd%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: cb11756ad08ef4d645360b90aadabeecee807e12
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=822a78c8-f6a3-446e-8248-f5a94564c4c7%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 2cac9263e09192abec69880eb5605e2ee497aed2
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=bc97fafd-c3fa-47b2-ad86-8184eb44ff74%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by lukemaurer** [comment]
> ### AWS CodeBuild CI Report
> 
>     * CodeBuild project: Dafny
> 
>     * Commit ID: [2cac926](https://github.com/dafny-lang/dafny/commit/2cac9263e09192abec69880eb5605e2ee497aed2)
> 
>     * Result: FAILED
> 
>     * [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=bc97fafd-c3fa-47b2-ad86-8184eb44ff74%2Fbuild.log) (available for 30 days)
> 
> 
> _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_

This looks spurious (something to do with thread scheduling).  It WFM, at any rate.

**Comment by robin-aws** [comment]
> > ### AWS CodeBuild CI Report
> > ```
> > * CodeBuild project: Dafny
> > 
> > * Commit ID: [2cac926](https://github.com/dafny-lang/dafny/commit/2cac9263e09192abec69880eb5605e2ee497aed2)
> > 
> > * Result: FAILED
> > 
> > * [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=bc97fafd-c3fa-47b2-ad86-8184eb44ff74%2Fbuild.log) (available for 30 days)
> > ```
> > 
> > 
> > _Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)_
> 
> This looks spurious (something to do with thread scheduling). It WFM, at any rate.

Known issue: #454 :(

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: ed1fb2850db4bccfbc97cfc280a242080407e88d
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ef479197-c5ef-4744-97b7-2fd0878eeb40%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 0c6f81417faef1e19e3337b5037ec0041bc4ace2
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ba353bc6-7c50-4836-aa95-e9365485f3e3%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: c78bba8f7b6a47b299c53c917567a67e6ae6cb95
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=b13d637b-0c14-45c7-b036-0767d55a7071%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by RustanLeino** [comment]
This is a PR against a new branch, java-type-descriptors, rather than master. I tried changing it before merging, but github gave me a scary warning. So, instead, I'll merge this into the java-type-descriptors branch, and will then merge that into master.

**Pull request merged**
