### PR TITLE
fix: Release lock before raising exception for improved recovery

### LINKED ISSUE #5913: Python MutableMap should release locks if unhandled exception is raised
### Dafny version

4.8.1

### Code to produce this issue

Code is here: https://github.com/dafny-lang/dafny/blob/f01af4a4e86a038ed4ea9f81464b2c9bca1955e4/Source/DafnyStandardLibraries/src/Std_Concurrent.py

### Command to run and resulting output

```code
lucmcdon@80a997335f93 Desktop % python3
Python 3.11.2 (main, Sep  3 2024, 12:49:51) [Clang 15.0.0 (clang-1500.3.9.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import Std_Concurrent
>>> m = Std_Concurrent.MutableMap()
>>> m.Put(1,2)  # Returns, no output
>>> m.Put(["lists aren't hashable"], "and result in TypeError")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/lucmcdon/Desktop/testdafny.py", line 45, in Put
    self.map[k] = v
    ~~~~~~~~^^^
TypeError: unhashable type: 'list'
>>> m.Put(1,2)  # Hangs indefinitely
```

### What happened?

The problem is the lock is not released if an exception is raised before the `Unlock` call.
The solution should be wrapping the internal logic in a `try`/`finally` block, ex.
```
def Put(self, k, v):
    self.lock.Lock__()
    try: 
        self.map[k] = v
    finally:
        self.lock.Unlock()
```
I tested this locally with the same commands as above, and the final `Put` no longer hangs.
You should also do this for other methods in the class.

This does not block me or impact me in any way as I don't use this class, but is worth noting.

### What type of operating system are you experiencing the problem on?

Mac

### PR DESCRIPTION
**Pull request by fabiomadge**
Fixes #5913.

### CODE REVIEW

**Comment by fabiomadge** [comment]
I think that's more trouble than it's worth. The map already has tests and this change is just about what I consider undefined behaviour.

**Comment by keyboardDrummer** [comment]
> this change is just about what I consider undefined behaviour.

It was reported by a user who ran into it and considered it a bug, so why not add a test to prevent it from re-occurring?

**Comment by fabiomadge** [comment]
Your understanding is correct. I'm not against adding the test, but I’m not convinced its worth _my_ time.

**Comment by fabiomadge** [comment]
Let me elaborate on what I meant by undefined behaviour. I can't think of a way of running into this issue from Dafny generated code. I believe the contract with the user stipulates that we provide a correct Dafny library, not one for general consumption from any Python codebase.
I also can't think of a precedent of tests without any Dafny code, so I am hesitant to break with it.

**Comment by keyboardDrummer** [comment]
> Let me elaborate on what I meant by undefined behaviour. I can't think of a way of running into this issue from Dafny generated code. I believe the contract with the user stipulates that we provide a correct Dafny library, not one for general consumption from any Python codebase.

That's fair.

> I also can't think of a precedent of tests without any Dafny code, so I am hesitant to break with it.

Me neither. You could use the littish tests for it but it would feel kind of hacky because you'd have a .dfy file with no actualy Dafny instructions, just shell commands to run some Python code.

**Review by keyboardDrummer — APPROVED** [review]

**Pull request merged**
