### PR TITLE
Don't expand stdin.dfy as a path

### LINKED ISSUE #1109: stdin.dfy doesn't work
It no longer works to specify stdin.dfy as the input file name, to make Dafny read from stdin.

### PR DESCRIPTION
**Pull request by jaylorch**
Fixes #1109.

### CODE REVIEW

**Comment by jaylorch** [comment]
There was an earlier discussion of this (before I moved it to this branch).  That discussion suggested that instead of doing this, we should use - instead of stdin.dfy, and we should also add a regression test for this.

**Comment by RustanLeino** [comment]
Hi @jaylorch , Would you like to implement the command-line switch (say, `-stdin`) for reading from standard in, rather than the `stdin.dfy` kludge (see #1109 and #1110), or would you prefer we merge the present PR into master for now?

**Comment by jaylorch** [comment]
The command-line switch sounds like a good idea. So no need to merge this PR into master; I'll implement -stdin.

**Comment by jaylorch** [comment]
OK, I just updated this pull request to implement using /stdin or -stdin instead of stdin.dfy.

**Comment by RustanLeino** [comment]
Nice. Can you please add a test case as well? (See the top 2 lines of, for example, `Test/git-issues/git-issue-1151.dfy` as a guide, but redirect standard in.)

**Comment by jaylorch** [comment]
Sure! I just added a test case.

**Review by RustanLeino — APPROVED** [review]

**Pull request merged**
