### PR TITLE
chore: Fixed all the broken links in the documentation

### PR DESCRIPTION
**Pull request by MikaelMayer**
This effort will probably break the PDF generation of the documentation, but I think we care more about the website.

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Comment by fabiomadge** [comment]
You're right, it does break the pdf. I had a related problem in #2188, maybe we should dump Jekyll and use pandoc for html generation as well
[DafnyRef.pdf](https://github.com/dafny-lang/dafny/files/8832945/DafnyRef.pdf)
.

**Comment by MikaelMayer** [comment]
> You're right, it does break the pdf in different ways. I had a related problem in #2188. Maybe we should dump Jekyll and use pandoc for html generation as well. [DafnyRef.pdf](https://github.com/dafny-lang/dafny/files/8832945/DafnyRef.pdf)

After looking at it, since I'm using `id="theId"`  in HTML tags and I removed `~ Equation {#theId}` to create references, it makes sense that they don't work in LaTeX anymore. Is there a way we can re-add these labels so that they work for both? Do you see any other breaking changes?

**Review by fabiomadge — APPROVED** [review]
It's undoubtedly better than the status quo, but it would be nice, if we could enable the references in the pdf version eventually.

**Comment by MikaelMayer** [comment]
> It's undoubtedly better than the status quo, but it would be nice, if we could enable the references in the pdf version eventually.

Yes, I agree, but I don't know how we could do that. A wrapper script before using pandoc to add `~ Equation ... ~` and move references when encountering an `id=""`?

**Pull request merged**
