### PR TITLE
chore: Remove unused field ResolvedUpdateExpr of SeqUpdateExpr

### PR DESCRIPTION
**Pull request by cpitclaudel**
ResolvedUpdateExpr in SeqUpdateExpr is never assigned; should it be?

### CODE REVIEW

**Review by MikaelMayer — CHANGES_REQUESTED** [review]
This documentation seems outdated. Can you please fix it?

**Comment by MikaelMayer** [comment]
Otherwise, great cleaning up !

**Comment by cpitclaudel** [comment]
Good catch, thanks!  Updated :)

**Review by MikaelMayer — APPROVED** [review]
Great job enhancing the documentation !

**Pull request merged**
