### PR TITLE
Introduce lvalue abstraction

### PR DESCRIPTION
**Pull request by lukemaurer**
(Comes after #522, though it doesn't really depend on it.)

An lvalue being something that can be on the left of the assignment operator,
an ILvalue is something we know how to render either as a value being read or a
location being written to.  Having this abstraction means that a backend can
specify that a particular expression must be assigned to using something
besides an actual assignment statement; this way a call to EmitAssignment may
not literally emit an assignment.  For example, the Java backend was not
properly implementing setter methods (see the included test case), but now
they're easy to implement using a custom ILvalue implementation (see
JavaCompiler.GetterSetterLvalue) without changes to the base class.  (The
MemberSelectObjIsTrait parameter to EmitMemberSelect, which was only there for
the Java backend, is no more.)

In particular, this paves the way for Java to use unboxed primitives, since
representing an array of T as T[] forces us to use arrays of boxed types, but
using a plain Object means we can't index into the array as an lvalue---we have
to call a method (such as one in java.lang.reflect.Array, though we'll use
something faster) instead of an assignment statement.

### CODE REVIEW

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: abd7d93b610fe1eb19aab56940c09edb84349a8d
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7c7a3b9b-7583-4731-b43e-725b8bd8e153%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 68c119ee2707e6d9741e4093c69fd0453b9a679f
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=703f10ff-d15e-4ddb-9c85-d23534367440%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 6105a60ed340088ebc07ab2fcd55e9548da54efe
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=4accb9a7-7916-4caf-a764-3e70043f6435%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 11c22ba367db8c3097b2e3df8c9551197547879a
* Result: SUCCEEDED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=ef53486b-76e9-442f-8e37-babb2ac8447c%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by robin-aws** [comment]
### AWS CodeBuild CI Report

* CodeBuild project: Dafny
* Commit ID: 01c455e3ecaa497db943360dde2242d69caa45c6
* Result: FAILED
* [Build Logs](https://g85ugprat7.execute-api.us-west-2.amazonaws.com/Prod/buildlogs?key=7a30754b-ac73-4742-9536-f2725eccc2d0%2Fbuild.log) (available for 30 days)

*Powered by [github-codebuild-logs](https://serverlessrepo.aws.amazon.com/applications/arn:aws:serverlessrepo:us-east-1:277187709615:applications~github-codebuild-logs), available on the [AWS Serverless Application Repository](https://aws.amazon.com/serverless/serverlessrepo/)*

**Comment by RustanLeino** [comment]
One of the tests is failing, but after merging this PR, I'm going to merge its successor (#524), whose tests all pass.

**Pull request merged**
