### PR TITLE
chore: enable test reports

### PR DESCRIPTION
**Pull request by fabiomadge**
`test-report.yaml` will not run smoothly until we give it some files. This might do the trick. Otherwise I propose disabling it for the time being.

### CODE REVIEW

**Review by keyboardDrummer — COMMENTED** [review]
What is change you've made that you're hoping will produce an effect?

**Comment by fabiomadge** [comment]
We now actually produce logs again when running the integration tests. We also let the reporting script handle downloading the correct artifact, which didn’t work before. This part isn’t tested, so it still might not work.

**Comment by keyboardDrummer** [comment]
Is it possible to fully test this on your own fork?

**Comment by fabiomadge** [comment]
No, it isn't, but I’ll set up a different testing org for other CI experiments I want to do.

**Comment by fabiomadge** [comment]
Confirmed to work in a separate repo.

**Review by keyboardDrummer — APPROVED** [review]

**Pull request merged**
