### PR TITLE
Merge Language Server Source

### PR DESCRIPTION
**Pull request by camrein**
As suggested in dafny-lang/language-server-csharp/issues/48, I am filing a PR to merge the sources into Dafny's main repository.
I have opted to keep the commit history of the language server. If you prefer not to include the history in this repository, I will prepare another PR.

PS: I currently drafted this PR since I still have to add the language server to the build process. Moreover, you can quickly take a look at the current state and provide some feedback if you think something doesn't fit in into the current file structure or something like that.

### CODE REVIEW

**Comment by camrein** [comment]
I think I am mostly done by now. However, I am unsure about the *LanguageServer.Test* project. I am aware that there's a separate Test folder where the tests are run through a script. Since the test project depends on the LanguageServer itself, it should be located in a common solution. Otherwise, its dependencies are not automatically updated upon changes. One option might be that we create a separate solution for the LanguageServer (or its tests).

As the last step (besides the considerations mentioned above), I have to add language server tests to the test/build pipeline.

**Comment by camrein** [comment]
The PR is ready for review. Unfortunately, I have not added a language server test for the release packages. Since the language server is a long-running process, I would need to add a change to process single requests. For example, a version output might be an option, but I can't really tell how reliable this test would be if there are missing dependencies.

**Comment by RustanLeino** [comment]
The code looks good. I didn't yet try building it on my own machine.

After we merge this, how do we do the 3.1 release? For example, do we first push out the binary Dafny release here and then, shortly thereafter but separately, do the release for the VS Code components?

**Review by RustanLeino — DISMISSED** [review]

**Comment by camrein** [comment]
> The code looks good. I didn't yet try building it on my own machine.

Great. There shouldn't be any difference to building Dafny itself since the language server is now part of the Dafny solution. However, running the unit tests requires a resolvable Z3 installation (e.g., copying it into the build dir). You can find the unit tests within Visual Studio's Test Explorer:

image

> After we merge this, how do we do the 3.1 release? For example, do we first push out the binary Dafny release here and then, shortly thereafter but separately, do the release for the VS Code components?

I have prepared the upgrade of the VSCode Extension in a new branch:
https://github.com/DafnyVSCode/ide-vscode/tree/prepare-v1.5.0

As soon as you release  Dafny 3.1, I will follow with the extension. You don't have to mind that new Dafny releases might break new (or even existing) VSCode setups, so feel free to release new versions. In contrast to the previous extension, the new one is always tied to a specific version of the language server. Moreover, everyone is free to configure the extension to use another language server and compiler installation than the one that is automatically grabbed - as long as the min version is met.

**Comment by RustanLeino** [comment]
@camrein I'm ready to merge this PR. You had requested that we save the revision history. Dafny is set to "Squash and merge", but I can temporarily change that and then accept this PR with a merge commit. I expect that will then let us delete the `add-language-server` branch, since the change history will then be incorporated into `master`. Does that sound like a good idea? Is my understanding of these things correct?

**Comment by camrein** [comment]
@RustanLeino If you prefer to squash the commits, feel free to do so. I just thought it might be convenient to be able to see some changes over time.
Yes, after a successful merger, you can delete this branch. Since there are no outstanding changes to make this PR compatible with the current master, feel free to merge it as soon as you're ready.

**Comment by RustanLeino** [comment]
Okay, I'll just squash it, then. After that, I'll work on getting Dafny 3.1 out today.

**Pull request merged**
