### PR TITLE
Enable command line completion

### PR DESCRIPTION
**Pull request by keyboardDrummer**
Enable the [parse] and [suggest] directives, the latter which should enable command line completion to work.

Hopefully fixes https://github.com/dafny-lang/dafny/issues/3190

https://learn.microsoft.com/en-us/dotnet/standard/commandline/syntax#directives

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Comment by MikaelMayer** [comment]
Can you please explain how this works?

**Comment by keyboardDrummer** [comment]
> Can you please explain how this works?

For CLI completions, the completion engine will call `dafny [suggest] ..normal arguments..` and use the output of that to provide completions to the CLI. Without this PR, `dafny [suggest]` doesn't work.

Once we merge this PR and publish a new CLI version, users still need to follow the steps here to get CLI completion working: https://learn.microsoft.com/en-us/dotnet/standard/commandline/tab-completion#enable-tab-completion

**Comment by MikaelMayer** [comment]
Can you please add documentation about how to enable it in our docs? After that I'll approve it.

**Comment by keyboardDrummer** [comment]
> Can you please add documentation about how to enable it in our docs? After that I'll approve it.

I would first like to see it actually work, but not sure how to test that without this change

**Review by MikaelMayer — APPROVED** [review]
Sounds good to me.

**Pull request merged**
