### PR TITLE
Language Server: Option to set the severity of info messages

### PR DESCRIPTION
**Pull request by camrein**
This PR enables users to change the severity of information messages (such as *tail recursive*) as requested in https://github.com/dafny-lang/ide-vscode/issues/42.

### CODE REVIEW

**Review by keyboardDrummer — COMMENTED** [review]
I wonder whether the language server is the right layer to solve this problem. You could also solve it in the LSP client, or in the client (VSCode). VSCode internally differentiates between error/warning/info/hint, just like LSP, so I would hope VSCode already allows you to configure how each of those is visualised in the IDE.

Here's an SO post that might also solve the customer problem: https://stackoverflow.com/a/48610661/93197

**Comment by camrein** [comment]
That's an excellent input. If that's a suitable solution, I'd definitely prefer not to include this change in the language server. However, we should probably mention it somewhere in the README.

PS: I have to mention that I was contacted about this earlier. Primarily because there's also noise in the *Problems* tab (that can be filtered), but also about the squiggles.

**Comment by keyboardDrummer** [comment]
> Primarily because there's also noise in the _Problems_ tab (that can be filtered), but also about the squiggles.

I get the impression that VSCode's/LSP's 'Information' level diagnostics are badly named and should not be used for arbitrary information but instead for calls to action such as refactoring hints. Some of the things the Dafny LSP server mentions as information, such as "tail recursive" and "decreases a.Length" don't fall into this category, and might be better exposed in tooltips.

One 'fix' might be to simply ignore all the information results from Dafny, or do you think there are important things there that customers must know?

**Comment by camrein** [comment]
As you proposed, we could simply opt to ignore Dafny's information messages. Unfortunately, I don't know how important/useful this information for existing Dafny users is. It might be interesting for newcomers to see what Dafny can infer, but probably noisy for experienced users. Another simple solution would be reducing the severity to *Hint*. That way, it won't appear in the *Problems* tab, but users can still see it when hovering over the code locations.
Since I don't know how important this feature is for existing users, I didn't want to make such a user-facing change so far.

@RustanLeino What is your opinion about displaying the information messages such as *tail recursive*? Do you think it's beneficial to leave them as is?

**Comment by keyboardDrummer** [comment]
Just my 2-cents, displaying them as hint seems good 👍

**Comment by camrein** [comment]
I'm closing this PR in favor of the recently merged #1432.

**Pull request closed without merging**
