### PR TITLE
feat(lsp): Show verification progress by boogie program

### PR DESCRIPTION
**Pull request by camrein**
This a small extension to the status reporting during verification. It intends to improve the UX by letting users know at which boogie program is currently being verified out of the total number of boogie programs (that is, the number of Dafny modules) to verify.

I drafted this PR for quick review if the intended UX improvement is actually valuable hence why I didn't fix the failing tests yet.

image

PS: If someone has a larger sample project and screenshot to see if it's actually displaying more than 1/1, that be great.
PPS: We could further improve upon this if we'd know the number of methods to verify in advance.

### CODE REVIEW

**Comment by cpitclaudel** [comment]
Won't it be confusing that the number doesn't always change when the string before it does?  For example, what will it show for this program?

```dafny
module A0 {
  method f0() returns (r: nat) { return 0; }
  method g0() returns (r: nat) { return 0; }
  method h0() returns (r: nat) { return 0; }
}

module A1 {
  method f1() returns (r: nat) { return 1; }
  method g1() returns (r: nat) { return 1; }
  method h1() returns (r: nat) { return 1; }
}

module A2 {
  method f2() returns (r: nat) { return 2; }
  method g2() returns (r: nat) { return 2; }
  method h2() returns (r: nat) { return 2; }
}
```

**Comment by camrein** [comment]
That was one of my concerns as well. That's why I was wondering if we could actually retrieve the number of boogie functions being verified. The example code you provided will be presented like this:
image

If there's any benefit for this information, we'd definitely have to make it clear that these numbers represent the modules being verifeid.

**Comment by MikaelMayer** [comment]
> If there's any benefit for this information, we'd definitely have to make it clear that these numbers represent the modules being verifeid.

To my experience, the Dafny extension is primarily used to display per-file feedback, and I don't expect usually more than 1 module per file (except when a user is trying to prototype a large-scale system). Thus, having a ratio per module will be confusing, especially because the number does not change when the name changes.

I would love if you could actually retrieve a number that will increase by 1 not per boogie program, but per method name change. That would be immediately useful.
I think you could do it the following way:

* Replace `CurrentProgram` by `MethodsVerified`
* Increment `MethodsVerified` not in the loop per boogie program, but where `ReportProgress` is called
* Replace `totalProgram` by `totalMethods`
* Compute `totalMethods` by going through the Dafny AST and manually computing the methods that Boogie is going to verify

**Comment by cpitclaudel** [comment]
> I don't expect usually more than 1 module per file

!! I find that very surprising: given that the IDE currently only gives per-file feedback, it's hard to edit things with tight dependencies that are spread across files.

**Comment by camrein** [comment]
Thanks for your suggestions @MikaelMayer. I was hoping there'd be a quicker way to retrieve the necessary information.

> !! I find that very surprising: given that the IDE currently only gives per-file feedback, it's hard to edit things with tight dependencies that are spread across files.

Making the language server verify the whole tree isn't a big deal. If I remember correctly, you'd have to set `DafnyOptions.VerifyAllModules` to `true`. You could do this here:
https://github.com/dafny-lang/dafny/blob/master/Source/DafnyLanguageServer/Language/DafnyProgramVerifier.cs#L47-L48

I have the feeling that this will have a huge impact on responsiveness. However, it depends on how well incomplete verifications can be canceled. Therefore, it might be worth giving it a try with a larger code base. We could also think about providing `/verifyAllModules` as a new command within VSCode.

**Comment by keyboardDrummer** [comment]
I'm working on changes to expose more information about individual proofs from Boogie to Dafny, which'll allow us to show the total number of proofs being verified. Consider pausing this PR until that information is available.

**Comment by cpitclaudel** [comment]
I think this feature is now available in the latest Dafny LSP :)

**Comment by camrein** [comment]
Nice! Closing this PR

**Pull request closed without merging**
