### PR TITLE
Don't expand stdin.dfy as a path

### LINKED ISSUE #1109: stdin.dfy doesn't work
It no longer works to specify stdin.dfy as the input file name, to make Dafny read from stdin.

### PR DESCRIPTION
**Pull request by jaylorch**
Fixes #1109

### CODE REVIEW

**Review by robin-aws — CHANGES_REQUESTED** [review]
Personally I wasn't even aware this was possible before! :) For the record I'm definitely not a fan of using such a magic file name, and would prefer an explicit switch like `/stdin` instead. Assuming this broke between 2.3 and 3.0, now would be the time to fix that since the major version bump allows the breaking change.

Regardless of what we decide there, we also badly need a regression test for this.

**Comment by davidcok** [comment]
Or use what other command-line tools do, namely ‘-‘ for stdin (e.g. diff)

**Comment by robin-aws** [comment]
I almost suggested `-` as well. I slightly prefer the switch since it's more "portable": `-` is more of a *nix system convention AFAIK, and I imagine it would feel a little strange on Windows.

**Comment by davidcok** [comment]
I could go with -stdin /stdin and - as equivalent alternatives

**Comment by jaylorch** [comment]
I agree that the magic name stdin.dfy is a bit weird as the way to do read from stdin.  I wasn't even aware of this Dafny feature until, when I was updating rise4fun.com/dafny to use Dafny 3.0.0, I discovered it relied on it.  And I definitely agree that a regression test is needed.

**Comment by jaylorch** [comment]
I want to use a different branch for this, so I'm closing this pull request.

**Pull request closed without merging**
