### PR TITLE
Attempt to build DafnyRef using Tectonic

### PR DESCRIPTION
**Pull request by atomb**
### Description
We've frequently had trouble building `DafnyRef.pdf` because installing TeXLive fails in some way. This attempts to use Tectonic, instead, to see if it fares better.

By submitting this pull request, I confirm that my contribution is made under the terms of the MIT license.

### CODE REVIEW

**Comment by atomb** [comment]
This changes the `build-refman` job to run in `ubuntu-latest` instead of `ubuntu-20.04`, so we'll have to change the list of required checks.

**Comment by keyboardDrummer** [comment]
> This changes the build-refman job to run in ubuntu-latest instead of ubuntu-20.04, so we'll have to change the list of required checks.

Why not use a static version, to prevent sudden breakages?

**Comment by atomb** [comment]
> > This changes the build-refman job to run in ubuntu-latest instead of ubuntu-20.04, so we'll have to change the list of required checks.
> 
> Why not use a static version, to prevent sudden breakages?

The `setup-tectonic` action advertises support only for `*-latest`, so that seems like the least likely to break in practice.

**Comment by keyboardDrummer** [comment]
> > > This changes the build-refman job to run in ubuntu-latest instead of ubuntu-20.04, so we'll have to change the list of required checks.
> > 
> > 
> > Why not use a static version, to prevent sudden breakages?
> 
> The `setup-tectonic` action advertises support only for `*-latest`, so that seems like the least likely to break in practice.

If we fix the version number of `setup-tectonic`, then we know it works for `ubuntu-20.04`, and we can fix that too. If everything is fixed, then we will have one less reason that CI suddenly breaks.

**Review by robin-aws — APPROVED** [review]

**Pull request merged**
