### PR TITLE
Compile map merge and map subtraction

### LINKED ISSUE #1044: Feature request: additional map operations
I'm noticing that building some basic map operations in user code is a common pattern, and while that exercise is a great way to learn the ropes with Dafny, it also means Dafny users have to spend a bunch of time getting that working instead of the more interesting work of proving correctness of their actual code!

Compared to sets, multisets, and sequences, maps feel like they are missing a few fundamental built-in operations. They could be defined in a standard library, but using operators will help with legibility and also open up the opportunity to optimize these very common operations in the compilers.

Namely, I propose adding the following two new operations:

1. Map "merging" using the `+` operator. The RHS would be another `map<T,U>` value. This would be associative but not commutative, just as sequence concatenation is. Mappings in the RHS would take precedence over those in the LHS where keys are duplicated.
2. Map "subtraction" using the `-` operator. The RHS should arguably be a `set<T>` rather than a `map<T, U>`.

### PR DESCRIPTION
**Pull request by RustanLeino**
The new map merge and map subtraction operations are now compiled to 5 languages.

Together with the merged PR https://github.com/dafny-lang/dafny/pull/1050, this addresses the points in Issue https://github.com/dafny-lang/dafny/issues/1044.

Closes #1044

### CODE REVIEW

**Review by robin-aws — CHANGES_REQUESTED** [review]
I didn't catch this in the previous PR, and it looks like the term was already present but inactive for some reason, but I really think the label should really be "MapMerge" (or similar) instead of "MapUnion". For me "Union" strongly implies something commutative and could be misleading. It might share an operator symbol with set union, but we call the sequence variant "Concat" rather than something like "SeqUnion".

**Comment by RustanLeino** [comment]
Good idea. I renamed "map union" to "map merge".

While we're at it, is there a better name for "map subtraction"? Something like "domain restriction" sounds more accurate, except that "domain restriction" usually says what to _keep_ of the domain, not what to _kick out_. "Domain reduction"? Is there a commonly used term for this?

**Comment by RustanLeino** [comment]
I checked Jean-Raymond Abrial's "Modeling in Event-B" book. It seems to call it "domain subtraction".

**Comment by robin-aws** [comment]
I have no issue with "subtraction" personally, I think it's perfectly intuitive here.

**Review by davidcok — APPROVED** [review]

**Pull request merged**
