### PR TITLE
Add documentation for getting Dafny toolchain developer help

### PR DESCRIPTION
**Pull request by keyboardDrummer**
Add documentation for getting Dafny toolchain developer help

```
Description:
  The Dafny CLI enables working with Dafny, a verification-aware programming language. Use 'dafny 
  /help' to see help for a previous CLI format.

Usage:
  Dafny [command] [options]

Options:
  --version                  Show version information
  -?, -h, --help             Show help and usage information
  --language-developer-help  Show help and usage information, including options designed for 
                             developing the Dafny language and toolchain.

Commands:
  resolve <file>                      Only check for parse and type resolution errors.
  ..
```
### Testing
Added a test

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Review by davidcok — CHANGES_REQUESTED** [review]
Is this replacing --dev? I presume the intent is to show all the options?

To me --language-developer-help is not quite right - as its tool developers as much as language developers. Something shorter? Even just --help-dev

**Comment by keyboardDrummer** [comment]
> Is this replacing --dev? I presume the intent is to show all the options?
> 
> To me --language-developer-help is not quite right - as its tool developers as much as language developers. Something shorter? Even just --help-dev

Does shortening developer to dev help? I think maybe I will focus on the features not on the persona, so `--toolchain-debugging-help`

**Comment by davidcok** [comment]
How about --help-debugging?
I like the --help first as to me it more clearly conveys it is a variation or expansion on --help

**Comment by keyboardDrummer** [comment]
Ok, how about `--help-debug-internals` or `--help-debug-toolchain` ?

**Comment by davidcok** [comment]
Of those I'd prefer --help-debug-internals (toolchain seems redundant in this context)
but I'd prefer --help-debug or --help-internal or --help-extra to that one.

**Comment by keyboardDrummer** [comment]
> I'd prefer --help-debug

`--help-debug` sound like it will help me debug my Dafny program, assuming the fault is the user written Dafny code, not in Dafny internals, so I think the name would be misleading.

I'm OK with `--help-internal` and both @davidcok and @atomb have suggested it, so let's go with that.

**Review by davidcok — APPROVED** [review]

**Pull request merged**
