### PR TITLE
A proposed fix for GitHub issue #684.

### PR DESCRIPTION
**Pull request by parno**

### CODE REVIEW

**Comment by davidcok** [comment]
As it is a compiler problem, configure the test to check all language targets.

**Comment by parno** [comment]
What's the necessary lit incantation to do that?

**Comment by davidcok** [comment]
Here is a common lit spec at the start of a .dfy test file:

// RUN: %dafny /compile:0 "%s" > "%t"
// RUN: %dafny /noVerify /compile:4 /compileTarget:cs "%s" >> "%t"
// RUN: %dafny /noVerify /compile:4 /compileTarget:js "%s" >> "%t"
// RUN: %dafny /noVerify /compile:4 /compileTarget:go "%s" >> "%t"
// RUN: %dafny /noVerify /compile:4 /compileTarget:java "%s" >> "%t"
// RUN: %diff "%s.expect" "%t"

Then you just run lit as usual on the file or folder

- David

**Comment by robin-aws** [comment]
Note my WIP test refactoring makes this a lot easier as it will be the default test case behaviour, and will automatically pick up new languages: #680

@parno I'd love to hear your opinion on that testing approach as well, especially since some of it could easily be used for other programming language implementations (such as https://github.com/microsoft/Armada for example :))

**Pull request merged**
