### PR TITLE
[Test Generation] Reduce memory footprint by reusing the same Boogie program for multiple test generation queries

### PR DESCRIPTION
**Pull request by Dargones**
In draft stage because boogie-org/boogie/pull/780 should be merged first.

This PR reduces the memory footprint / running time of test generation by reusing the same in-memory representation of a Boogie program. Previously, Dafny would have to copy the entire Boogie program to a string and parse/resolve/typecheck it again for every new test Dafny generates. With some minor changes to Boogie, this deep-copy procedure is no longer necessary in Block and InlinedBlock modes (but still necessary for Path-based test generation - this is something I will have to work next)

<small>By submitting this pull request, I confirm that my contribution is made under the terms of the [MIT license](https://github.com/dafny-lang/dafny/blob/master/LICENSE.txt).</small>

### CODE REVIEW

**Comment by atomb** [comment]
I think this looks good. I'll give it a full review once https://github.com/boogie-org/boogie/pull/780 is merged and released, since this PR will have to be updated to take advantage of that release.

**Comment by Dargones** [comment]
Thank you, Aaron! Could you create a new Boogie release, so that I can update this PR?

**Comment by atomb** [comment]
I'll put the release out as soon as https://github.com/boogie-org/boogie/pull/783 is merged to bump the version number.

**Review by atomb — APPROVED** [review]
Looks good! I think it's ready to merge once that reference manual build issue is resolved.

**Pull request merged**
