### PR TITLE
Enable integration tests to run with the Rust backend in CI

### PR DESCRIPTION
**Pull request by shadaj**
Enable integration tests to run with the Rust backend in CI

### CODE REVIEW

**Comment by shadaj** [comment]
Do not update the branch for now, https://github.com/dafny-lang/dafny/pull/4658 breaks the Rust backend pretty badly becaus the `nat` newtype is never emitted.

**Comment by shadaj** [comment]
Okay, maybe it's not https://github.com/dafny-lang/dafny/pull/4658; but something is definitely still wrong with the `_System` module never being emitted.

**Comment by shadaj** [comment]
Okay, it is definitely #4658. Tests run fine locally but in CI this PR is merged with main so tests fail due to missing `_System`.

**Comment by shadaj** [comment]
@jtristan ready to go assuming that CI passes!

**Review by jtristan — APPROVED** [review]

**Pull request merged**
